//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhimHang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public long CommentsId { get; set; }
        public string Message { get; set; }
        public int PostedBy { get; set; }
        public int CommentBy { get; set; }
        public System.DateTime PostedDate { get; set; }
    
        public virtual UserLogin UserLogin { get; set; }
        public virtual RecommendStock RecommendStock { get; set; }
    }
}
