//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhimHang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class stox_tb_HOSE_Trading
    {
        public long ID { get; set; }
        public Nullable<int> StockNo { get; set; }
        public string StockSymbol { get; set; }
        public string StockType { get; set; }
        public Nullable<decimal> Ceiling { get; set; }
        public Nullable<decimal> Floor { get; set; }
        public Nullable<double> BigLotValue { get; set; }
        public string SecurityName { get; set; }
        public string SectorNo { get; set; }
        public string Designated { get; set; }
        public string Suspension { get; set; }
        public string Delist { get; set; }
        public string HaltResumeFlag { get; set; }
        public string Split { get; set; }
        public string Benefit { get; set; }
        public string Meeting { get; set; }
        public string Notice { get; set; }
        public string ClientIDRequest { get; set; }
        public Nullable<int> CouponRate { get; set; }
        public string IssueDate { get; set; }
        public string MatureDate { get; set; }
        public Nullable<decimal> AvrPrice { get; set; }
        public Nullable<int> ParValue { get; set; }
        public string SDCFlag { get; set; }
        public Nullable<decimal> PriorClosePrice { get; set; }
        public string PriorCloseDate { get; set; }
        public Nullable<decimal> ProjectOpen { get; set; }
        public Nullable<decimal> OpenPrice { get; set; }
        public Nullable<decimal> Last { get; set; }
        public Nullable<decimal> LastVol { get; set; }
        public Nullable<double> LastVal { get; set; }
        public Nullable<decimal> Highest { get; set; }
        public Nullable<decimal> Lowest { get; set; }
        public Nullable<double> Totalshare { get; set; }
        public Nullable<double> TotalValue { get; set; }
        public Nullable<int> AccumulateDeal { get; set; }
        public Nullable<int> BigDeal { get; set; }
        public Nullable<decimal> BigVol { get; set; }
        public Nullable<double> BigVal { get; set; }
        public Nullable<int> OddDeal { get; set; }
        public Nullable<decimal> OddVol { get; set; }
        public Nullable<double> OddVal { get; set; }
        public Nullable<decimal> Best1Bid { get; set; }
        public Nullable<decimal> Best1BidVolume { get; set; }
        public Nullable<decimal> Best2Bid { get; set; }
        public Nullable<decimal> Best2BidVolume { get; set; }
        public Nullable<decimal> Best3Bid { get; set; }
        public Nullable<decimal> Best3BidVolume { get; set; }
        public Nullable<decimal> Best1Offer { get; set; }
        public Nullable<decimal> Best1OfferVolume { get; set; }
        public Nullable<decimal> Best2Offer { get; set; }
        public Nullable<decimal> Best2OfferVolume { get; set; }
        public Nullable<decimal> Best3Offer { get; set; }
        public Nullable<decimal> Best3OfferVolume { get; set; }
        public Nullable<System.DateTime> DateReport { get; set; }
        public Nullable<decimal> CurrentRoom { get; set; }
        public Nullable<decimal> TotalRoom { get; set; }
        public Nullable<decimal> Match1 { get; set; }
        public Nullable<decimal> MatchVolume1 { get; set; }
        public Nullable<decimal> Match2 { get; set; }
        public Nullable<decimal> MatchVolume2 { get; set; }
        public Nullable<decimal> Other_room { get; set; }
        public Nullable<decimal> Room { get; set; }
        public Nullable<decimal> SellPrice3 { get; set; }
        public Nullable<decimal> SellPrice2 { get; set; }
        public Nullable<decimal> SellPrice1 { get; set; }
        public Nullable<decimal> BuyPrice3 { get; set; }
        public Nullable<decimal> BuyPrice2 { get; set; }
        public Nullable<decimal> BuyPrice1 { get; set; }
        public Nullable<int> SellQtty3 { get; set; }
        public Nullable<int> SellQtty2 { get; set; }
        public Nullable<int> SellQtty1 { get; set; }
        public Nullable<int> BuyQtty3 { get; set; }
        public Nullable<int> BuyQtty2 { get; set; }
        public Nullable<int> BuyQtty1 { get; set; }
        public Nullable<decimal> ChangePrice { get; set; }
        public Nullable<decimal> ClosePrice_Adjusted { get; set; }
        public Nullable<double> Rate_Adjusted { get; set; }
        public Nullable<double> Highest_Adjusted { get; set; }
        public Nullable<double> Lowest_Adjusted { get; set; }
        public Nullable<double> KLGD_ThoaThuan { get; set; }
        public Nullable<double> GTGD_ThoaThuan { get; set; }
        public Nullable<double> OpenPrice_Adjusted { get; set; }
    }
}
