//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhimHang.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class StoxDataEntities : DbContext
    {
        public StoxDataEntities()
            : base("name=StoxDataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<stox_tb_Company> stox_tb_Company { get; set; }
        public virtual DbSet<stox_tb_Ratio> stox_tb_Ratio { get; set; }
        public virtual DbSet<stox_tb_HOSE_Trading> stox_tb_HOSE_Trading { get; set; }
        public virtual DbSet<stox_tb_StocksInfo> stox_tb_StocksInfo { get; set; }
    }
}
