//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18213
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vfs.WebCrawler.Destination.Business {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Vfs.WebCrawler.Destination.Business.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create ExtensionMessage Exception..
        /// </summary>
        internal static string BusinessCreateExtensionMessageException {
            get {
                return ResourceManager.GetString("BusinessCreateExtensionMessageException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create ExtensionMessage From Reader Exception..
        /// </summary>
        internal static string BusinessCreateExtensionMessageFromReaderException {
            get {
                return ResourceManager.GetString("BusinessCreateExtensionMessageFromReaderException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create ExtensionMessageLog Exception..
        /// </summary>
        internal static string BusinessCreateExtensionMessageLogException {
            get {
                return ResourceManager.GetString("BusinessCreateExtensionMessageLogException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create ExtensionMessageLog From Reader Exception..
        /// </summary>
        internal static string BusinessCreateExtensionMessageLogFromReaderException {
            get {
                return ResourceManager.GetString("BusinessCreateExtensionMessageLogFromReaderException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create RelatedMessagelog Exception..
        /// </summary>
        internal static string BusinessCreateRelatedMessagelogException {
            get {
                return ResourceManager.GetString("BusinessCreateRelatedMessagelogException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create RelatedMessagelog From Reader Exception..
        /// </summary>
        internal static string BusinessCreateRelatedMessagelogFromReaderException {
            get {
                return ResourceManager.GetString("BusinessCreateRelatedMessagelogFromReaderException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create stock_New Exception..
        /// </summary>
        internal static string BusinessCreatestock_NewException {
            get {
                return ResourceManager.GetString("BusinessCreatestock_NewException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create stock_New From Reader Exception..
        /// </summary>
        internal static string BusinessCreatestock_NewFromReaderException {
            get {
                return ResourceManager.GetString("BusinessCreatestock_NewFromReaderException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create stock_NewsGroup Exception..
        /// </summary>
        internal static string BusinessCreatestock_NewsGroupException {
            get {
                return ResourceManager.GetString("BusinessCreatestock_NewsGroupException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create stock_NewsGroup From Reader Exception..
        /// </summary>
        internal static string BusinessCreatestock_NewsGroupFromReaderException {
            get {
                return ResourceManager.GetString("BusinessCreatestock_NewsGroupFromReaderException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create stock_Symbol Exception..
        /// </summary>
        internal static string BusinessCreatestock_SymbolException {
            get {
                return ResourceManager.GetString("BusinessCreatestock_SymbolException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create stock_Symbol From Reader Exception..
        /// </summary>
        internal static string BusinessCreatestock_SymbolFromReaderException {
            get {
                return ResourceManager.GetString("BusinessCreatestock_SymbolFromReaderException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create stock_SymbolPermLong Exception..
        /// </summary>
        internal static string BusinessCreatestock_SymbolPermLongException {
            get {
                return ResourceManager.GetString("BusinessCreatestock_SymbolPermLongException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create stock_SymbolPermLong From Reader Exception..
        /// </summary>
        internal static string BusinessCreatestock_SymbolPermLongFromReaderException {
            get {
                return ResourceManager.GetString("BusinessCreatestock_SymbolPermLongFromReaderException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete ExtensionMessage Exception..
        /// </summary>
        internal static string BusinessDeleteExtensionMessageException {
            get {
                return ResourceManager.GetString("BusinessDeleteExtensionMessageException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete ExtensionMessageLog Exception..
        /// </summary>
        internal static string BusinessDeleteExtensionMessageLogException {
            get {
                return ResourceManager.GetString("BusinessDeleteExtensionMessageLogException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete RelatedMessagelog Exception..
        /// </summary>
        internal static string BusinessDeleteRelatedMessagelogException {
            get {
                return ResourceManager.GetString("BusinessDeleteRelatedMessagelogException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete stock_New Exception..
        /// </summary>
        internal static string BusinessDeletestock_NewException {
            get {
                return ResourceManager.GetString("BusinessDeletestock_NewException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete stock_NewsGroup Exception..
        /// </summary>
        internal static string BusinessDeletestock_NewsGroupException {
            get {
                return ResourceManager.GetString("BusinessDeletestock_NewsGroupException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete stock_Symbol Exception..
        /// </summary>
        internal static string BusinessDeletestock_SymbolException {
            get {
                return ResourceManager.GetString("BusinessDeletestock_SymbolException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete stock_SymbolPermLong Exception..
        /// </summary>
        internal static string BusinessDeletestock_SymbolPermLongException {
            get {
                return ResourceManager.GetString("BusinessDeletestock_SymbolPermLongException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get ExtensionMessage Exception..
        /// </summary>
        internal static string BusinessGetExtensionMessageException {
            get {
                return ResourceManager.GetString("BusinessGetExtensionMessageException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get ExtensionMessage List Exception..
        /// </summary>
        internal static string BusinessGetExtensionMessageListException {
            get {
                return ResourceManager.GetString("BusinessGetExtensionMessageListException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get ExtensionMessageLog Exception..
        /// </summary>
        internal static string BusinessGetExtensionMessageLogException {
            get {
                return ResourceManager.GetString("BusinessGetExtensionMessageLogException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get ExtensionMessageLog List Exception..
        /// </summary>
        internal static string BusinessGetExtensionMessageLogListException {
            get {
                return ResourceManager.GetString("BusinessGetExtensionMessageLogListException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get RelatedMessagelog Exception..
        /// </summary>
        internal static string BusinessGetRelatedMessagelogException {
            get {
                return ResourceManager.GetString("BusinessGetRelatedMessagelogException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get RelatedMessagelog List Exception..
        /// </summary>
        internal static string BusinessGetRelatedMessagelogListException {
            get {
                return ResourceManager.GetString("BusinessGetRelatedMessagelogListException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get stock_New Exception..
        /// </summary>
        internal static string BusinessGetstock_NewException {
            get {
                return ResourceManager.GetString("BusinessGetstock_NewException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get stock_New List Exception..
        /// </summary>
        internal static string BusinessGetstock_NewListException {
            get {
                return ResourceManager.GetString("BusinessGetstock_NewListException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get stock_NewsGroup Exception..
        /// </summary>
        internal static string BusinessGetstock_NewsGroupException {
            get {
                return ResourceManager.GetString("BusinessGetstock_NewsGroupException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get stock_NewsGroup List Exception..
        /// </summary>
        internal static string BusinessGetstock_NewsGroupListException {
            get {
                return ResourceManager.GetString("BusinessGetstock_NewsGroupListException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get stock_Symbol Exception..
        /// </summary>
        internal static string BusinessGetstock_SymbolException {
            get {
                return ResourceManager.GetString("BusinessGetstock_SymbolException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get stock_Symbol List Exception..
        /// </summary>
        internal static string BusinessGetstock_SymbolListException {
            get {
                return ResourceManager.GetString("BusinessGetstock_SymbolListException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get stock_SymbolPermLong Exception..
        /// </summary>
        internal static string BusinessGetstock_SymbolPermLongException {
            get {
                return ResourceManager.GetString("BusinessGetstock_SymbolPermLongException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get stock_SymbolPermLong List Exception..
        /// </summary>
        internal static string BusinessGetstock_SymbolPermLongListException {
            get {
                return ResourceManager.GetString("BusinessGetstock_SymbolPermLongListException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Stock Information Exception.
        /// </summary>
        internal static string BusinessImport_UpdateStockInformationException {
            get {
                return ResourceManager.GetString("BusinessImport_UpdateStockInformationException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update ExtensionMessage Exception..
        /// </summary>
        internal static string BusinessUpdateExtensionMessageException {
            get {
                return ResourceManager.GetString("BusinessUpdateExtensionMessageException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update ExtensionMessageLog Exception..
        /// </summary>
        internal static string BusinessUpdateExtensionMessageLogException {
            get {
                return ResourceManager.GetString("BusinessUpdateExtensionMessageLogException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update RelatedMessagelog Exception..
        /// </summary>
        internal static string BusinessUpdateRelatedMessagelogException {
            get {
                return ResourceManager.GetString("BusinessUpdateRelatedMessagelogException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update stock_New Exception..
        /// </summary>
        internal static string BusinessUpdatestock_NewException {
            get {
                return ResourceManager.GetString("BusinessUpdatestock_NewException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update stock_NewsGroup Exception..
        /// </summary>
        internal static string BusinessUpdatestock_NewsGroupException {
            get {
                return ResourceManager.GetString("BusinessUpdatestock_NewsGroupException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update stock_Symbol Exception..
        /// </summary>
        internal static string BusinessUpdatestock_SymbolException {
            get {
                return ResourceManager.GetString("BusinessUpdatestock_SymbolException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update stock_SymbolPermLong Exception..
        /// </summary>
        internal static string BusinessUpdatestock_SymbolPermLongException {
            get {
                return ResourceManager.GetString("BusinessUpdatestock_SymbolPermLongException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create ExtensionMessage Exception..
        /// </summary>
        internal static string DataAccessCreateExtensionMessageException {
            get {
                return ResourceManager.GetString("DataAccessCreateExtensionMessageException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create ExtensionMessage From Reader Exception..
        /// </summary>
        internal static string DataAccessCreateExtensionMessageFromReaderException {
            get {
                return ResourceManager.GetString("DataAccessCreateExtensionMessageFromReaderException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create ExtensionMessageLog Exception..
        /// </summary>
        internal static string DataAccessCreateExtensionMessageLogException {
            get {
                return ResourceManager.GetString("DataAccessCreateExtensionMessageLogException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create ExtensionMessageLog From Reader Exception..
        /// </summary>
        internal static string DataAccessCreateExtensionMessageLogFromReaderException {
            get {
                return ResourceManager.GetString("DataAccessCreateExtensionMessageLogFromReaderException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete ExtensionMessage Exception..
        /// </summary>
        internal static string DataAccessDeleteExtensionMessageException {
            get {
                return ResourceManager.GetString("DataAccessDeleteExtensionMessageException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete ExtensionMessageLog Exception..
        /// </summary>
        internal static string DataAccessDeleteExtensionMessageLogException {
            get {
                return ResourceManager.GetString("DataAccessDeleteExtensionMessageLogException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get ExtensionMessage Exception..
        /// </summary>
        internal static string DataAccessGetExtensionMessageException {
            get {
                return ResourceManager.GetString("DataAccessGetExtensionMessageException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get ExtensionMessage List Exception..
        /// </summary>
        internal static string DataAccessGetExtensionMessageListException {
            get {
                return ResourceManager.GetString("DataAccessGetExtensionMessageListException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get ExtensionMessageLog Exception..
        /// </summary>
        internal static string DataAccessGetExtensionMessageLogException {
            get {
                return ResourceManager.GetString("DataAccessGetExtensionMessageLogException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get ExtensionMessageLog List Exception..
        /// </summary>
        internal static string DataAccessGetExtensionMessageLogListException {
            get {
                return ResourceManager.GetString("DataAccessGetExtensionMessageLogListException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update ExtensionMessage Exception..
        /// </summary>
        internal static string DataAccessUpdateExtensionMessageException {
            get {
                return ResourceManager.GetString("DataAccessUpdateExtensionMessageException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update ExtensionMessageLog Exception..
        /// </summary>
        internal static string DataAccessUpdateExtensionMessageLogException {
            get {
                return ResourceManager.GetString("DataAccessUpdateExtensionMessageLogException", resourceCulture);
            }
        }
    }
}
