//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18213
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vfs.WebCrawler.Destination.Data {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Vfs.WebCrawler.Destination.Data.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create ExtensionMessage Exception..
        /// </summary>
        internal static string DataAccessCreateExtensionMessageException {
            get {
                return ResourceManager.GetString("DataAccessCreateExtensionMessageException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create ExtensionMessage Exception..
        /// </summary>
        internal static string DataAccessCreateExtensionMessageException1 {
            get {
                return ResourceManager.GetString("DataAccessCreateExtensionMessageException1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create ExtensionMessage Exception..
        /// </summary>
        internal static string DataAccessCreateExtensionMessageException2 {
            get {
                return ResourceManager.GetString("DataAccessCreateExtensionMessageException2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create ExtensionMessage From Reader Exception..
        /// </summary>
        internal static string DataAccessCreateExtensionMessageFromReaderException {
            get {
                return ResourceManager.GetString("DataAccessCreateExtensionMessageFromReaderException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create ExtensionMessage From Reader Exception..
        /// </summary>
        internal static string DataAccessCreateExtensionMessageFromReaderException1 {
            get {
                return ResourceManager.GetString("DataAccessCreateExtensionMessageFromReaderException1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create ExtensionMessage From Reader Exception..
        /// </summary>
        internal static string DataAccessCreateExtensionMessageFromReaderException2 {
            get {
                return ResourceManager.GetString("DataAccessCreateExtensionMessageFromReaderException2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create ExtensionMessageLog Exception..
        /// </summary>
        internal static string DataAccessCreateExtensionMessageLogException {
            get {
                return ResourceManager.GetString("DataAccessCreateExtensionMessageLogException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create ExtensionMessageLog Exception..
        /// </summary>
        internal static string DataAccessCreateExtensionMessageLogException1 {
            get {
                return ResourceManager.GetString("DataAccessCreateExtensionMessageLogException1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create ExtensionMessageLog Exception..
        /// </summary>
        internal static string DataAccessCreateExtensionMessageLogException2 {
            get {
                return ResourceManager.GetString("DataAccessCreateExtensionMessageLogException2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create ExtensionMessageLog From Reader Exception..
        /// </summary>
        internal static string DataAccessCreateExtensionMessageLogFromReaderException {
            get {
                return ResourceManager.GetString("DataAccessCreateExtensionMessageLogFromReaderException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create ExtensionMessageLog From Reader Exception..
        /// </summary>
        internal static string DataAccessCreateExtensionMessageLogFromReaderException1 {
            get {
                return ResourceManager.GetString("DataAccessCreateExtensionMessageLogFromReaderException1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create ExtensionMessageLog From Reader Exception..
        /// </summary>
        internal static string DataAccessCreateExtensionMessageLogFromReaderException2 {
            get {
                return ResourceManager.GetString("DataAccessCreateExtensionMessageLogFromReaderException2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create RelatedMessagelog Exception..
        /// </summary>
        internal static string DataAccessCreateRelatedMessagelogException {
            get {
                return ResourceManager.GetString("DataAccessCreateRelatedMessagelogException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create RelatedMessagelog From Reader Exception..
        /// </summary>
        internal static string DataAccessCreateRelatedMessagelogFromReaderException {
            get {
                return ResourceManager.GetString("DataAccessCreateRelatedMessagelogFromReaderException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create stock_New Exception..
        /// </summary>
        internal static string DataAccessCreatestock_NewException {
            get {
                return ResourceManager.GetString("DataAccessCreatestock_NewException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create stock_New From Reader Exception..
        /// </summary>
        internal static string DataAccessCreatestock_NewFromReaderException {
            get {
                return ResourceManager.GetString("DataAccessCreatestock_NewFromReaderException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create stock_NewsGroup Exception..
        /// </summary>
        internal static string DataAccessCreatestock_NewsGroupException {
            get {
                return ResourceManager.GetString("DataAccessCreatestock_NewsGroupException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create stock_NewsGroup From Reader Exception..
        /// </summary>
        internal static string DataAccessCreatestock_NewsGroupFromReaderException {
            get {
                return ResourceManager.GetString("DataAccessCreatestock_NewsGroupFromReaderException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create stock_Symbol Exception..
        /// </summary>
        internal static string DataAccessCreatestock_SymbolException {
            get {
                return ResourceManager.GetString("DataAccessCreatestock_SymbolException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create stock_Symbol From Reader Exception..
        /// </summary>
        internal static string DataAccessCreatestock_SymbolFromReaderException {
            get {
                return ResourceManager.GetString("DataAccessCreatestock_SymbolFromReaderException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create stock_SymbolPermLong Exception..
        /// </summary>
        internal static string DataAccessCreatestock_SymbolPermLongException {
            get {
                return ResourceManager.GetString("DataAccessCreatestock_SymbolPermLongException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create stock_SymbolPermLong From Reader Exception..
        /// </summary>
        internal static string DataAccessCreatestock_SymbolPermLongFromReaderException {
            get {
                return ResourceManager.GetString("DataAccessCreatestock_SymbolPermLongFromReaderException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete ExtensionMessage Exception..
        /// </summary>
        internal static string DataAccessDeleteExtensionMessageException {
            get {
                return ResourceManager.GetString("DataAccessDeleteExtensionMessageException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete ExtensionMessage Exception..
        /// </summary>
        internal static string DataAccessDeleteExtensionMessageException1 {
            get {
                return ResourceManager.GetString("DataAccessDeleteExtensionMessageException1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete ExtensionMessage Exception..
        /// </summary>
        internal static string DataAccessDeleteExtensionMessageException2 {
            get {
                return ResourceManager.GetString("DataAccessDeleteExtensionMessageException2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete ExtensionMessageLog Exception..
        /// </summary>
        internal static string DataAccessDeleteExtensionMessageLogException {
            get {
                return ResourceManager.GetString("DataAccessDeleteExtensionMessageLogException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete ExtensionMessageLog Exception..
        /// </summary>
        internal static string DataAccessDeleteExtensionMessageLogException1 {
            get {
                return ResourceManager.GetString("DataAccessDeleteExtensionMessageLogException1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete ExtensionMessageLog Exception..
        /// </summary>
        internal static string DataAccessDeleteExtensionMessageLogException2 {
            get {
                return ResourceManager.GetString("DataAccessDeleteExtensionMessageLogException2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete RelatedMessagelog Exception..
        /// </summary>
        internal static string DataAccessDeleteRelatedMessagelogException {
            get {
                return ResourceManager.GetString("DataAccessDeleteRelatedMessagelogException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete stock_New Exception..
        /// </summary>
        internal static string DataAccessDeletestock_NewException {
            get {
                return ResourceManager.GetString("DataAccessDeletestock_NewException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete stock_NewsGroup Exception..
        /// </summary>
        internal static string DataAccessDeletestock_NewsGroupException {
            get {
                return ResourceManager.GetString("DataAccessDeletestock_NewsGroupException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete stock_Symbol Exception..
        /// </summary>
        internal static string DataAccessDeletestock_SymbolException {
            get {
                return ResourceManager.GetString("DataAccessDeletestock_SymbolException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete stock_SymbolPermLong Exception..
        /// </summary>
        internal static string DataAccessDeletestock_SymbolPermLongException {
            get {
                return ResourceManager.GetString("DataAccessDeletestock_SymbolPermLongException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get ExtensionMessage Exception..
        /// </summary>
        internal static string DataAccessGetExtensionMessageException {
            get {
                return ResourceManager.GetString("DataAccessGetExtensionMessageException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get ExtensionMessage Exception..
        /// </summary>
        internal static string DataAccessGetExtensionMessageException1 {
            get {
                return ResourceManager.GetString("DataAccessGetExtensionMessageException1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get ExtensionMessage Exception..
        /// </summary>
        internal static string DataAccessGetExtensionMessageException2 {
            get {
                return ResourceManager.GetString("DataAccessGetExtensionMessageException2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get ExtensionMessage List Exception..
        /// </summary>
        internal static string DataAccessGetExtensionMessageListException {
            get {
                return ResourceManager.GetString("DataAccessGetExtensionMessageListException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get ExtensionMessage List Exception..
        /// </summary>
        internal static string DataAccessGetExtensionMessageListException1 {
            get {
                return ResourceManager.GetString("DataAccessGetExtensionMessageListException1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get ExtensionMessage List Exception..
        /// </summary>
        internal static string DataAccessGetExtensionMessageListException2 {
            get {
                return ResourceManager.GetString("DataAccessGetExtensionMessageListException2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get ExtensionMessageLog Exception..
        /// </summary>
        internal static string DataAccessGetExtensionMessageLogException {
            get {
                return ResourceManager.GetString("DataAccessGetExtensionMessageLogException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get ExtensionMessageLog Exception..
        /// </summary>
        internal static string DataAccessGetExtensionMessageLogException1 {
            get {
                return ResourceManager.GetString("DataAccessGetExtensionMessageLogException1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get ExtensionMessageLog Exception..
        /// </summary>
        internal static string DataAccessGetExtensionMessageLogException2 {
            get {
                return ResourceManager.GetString("DataAccessGetExtensionMessageLogException2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get ExtensionMessageLog List Exception..
        /// </summary>
        internal static string DataAccessGetExtensionMessageLogListException {
            get {
                return ResourceManager.GetString("DataAccessGetExtensionMessageLogListException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get ExtensionMessageLog List Exception..
        /// </summary>
        internal static string DataAccessGetExtensionMessageLogListException1 {
            get {
                return ResourceManager.GetString("DataAccessGetExtensionMessageLogListException1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get ExtensionMessageLog List Exception..
        /// </summary>
        internal static string DataAccessGetExtensionMessageLogListException2 {
            get {
                return ResourceManager.GetString("DataAccessGetExtensionMessageLogListException2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get RelatedMessagelog Exception..
        /// </summary>
        internal static string DataAccessGetRelatedMessagelogException {
            get {
                return ResourceManager.GetString("DataAccessGetRelatedMessagelogException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get RelatedMessagelog List Exception..
        /// </summary>
        internal static string DataAccessGetRelatedMessagelogListException {
            get {
                return ResourceManager.GetString("DataAccessGetRelatedMessagelogListException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get stock_New Exception..
        /// </summary>
        internal static string DataAccessGetstock_NewException {
            get {
                return ResourceManager.GetString("DataAccessGetstock_NewException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get stock_New List Exception..
        /// </summary>
        internal static string DataAccessGetstock_NewListException {
            get {
                return ResourceManager.GetString("DataAccessGetstock_NewListException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get stock_NewsGroup Exception..
        /// </summary>
        internal static string DataAccessGetstock_NewsGroupException {
            get {
                return ResourceManager.GetString("DataAccessGetstock_NewsGroupException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get stock_NewsGroup List Exception..
        /// </summary>
        internal static string DataAccessGetstock_NewsGroupListException {
            get {
                return ResourceManager.GetString("DataAccessGetstock_NewsGroupListException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get stock_Symbol Exception..
        /// </summary>
        internal static string DataAccessGetstock_SymbolException {
            get {
                return ResourceManager.GetString("DataAccessGetstock_SymbolException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get stock_Symbol List Exception..
        /// </summary>
        internal static string DataAccessGetstock_SymbolListException {
            get {
                return ResourceManager.GetString("DataAccessGetstock_SymbolListException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get stock_SymbolPermLong Exception..
        /// </summary>
        internal static string DataAccessGetstock_SymbolPermLongException {
            get {
                return ResourceManager.GetString("DataAccessGetstock_SymbolPermLongException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get stock_SymbolPermLong List Exception..
        /// </summary>
        internal static string DataAccessGetstock_SymbolPermLongListException {
            get {
                return ResourceManager.GetString("DataAccessGetstock_SymbolPermLongListException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update ExtensionMessage Exception..
        /// </summary>
        internal static string DataAccessUpdateExtensionMessageException {
            get {
                return ResourceManager.GetString("DataAccessUpdateExtensionMessageException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update ExtensionMessage Exception..
        /// </summary>
        internal static string DataAccessUpdateExtensionMessageException1 {
            get {
                return ResourceManager.GetString("DataAccessUpdateExtensionMessageException1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update ExtensionMessage Exception..
        /// </summary>
        internal static string DataAccessUpdateExtensionMessageException2 {
            get {
                return ResourceManager.GetString("DataAccessUpdateExtensionMessageException2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update ExtensionMessageLog Exception..
        /// </summary>
        internal static string DataAccessUpdateExtensionMessageLogException {
            get {
                return ResourceManager.GetString("DataAccessUpdateExtensionMessageLogException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update ExtensionMessageLog Exception..
        /// </summary>
        internal static string DataAccessUpdateExtensionMessageLogException1 {
            get {
                return ResourceManager.GetString("DataAccessUpdateExtensionMessageLogException1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update ExtensionMessageLog Exception..
        /// </summary>
        internal static string DataAccessUpdateExtensionMessageLogException2 {
            get {
                return ResourceManager.GetString("DataAccessUpdateExtensionMessageLogException2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update RelatedMessagelog Exception..
        /// </summary>
        internal static string DataAccessUpdateRelatedMessagelogException {
            get {
                return ResourceManager.GetString("DataAccessUpdateRelatedMessagelogException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update stock_New Exception..
        /// </summary>
        internal static string DataAccessUpdatestock_NewException {
            get {
                return ResourceManager.GetString("DataAccessUpdatestock_NewException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update stock_NewsGroup Exception..
        /// </summary>
        internal static string DataAccessUpdatestock_NewsGroupException {
            get {
                return ResourceManager.GetString("DataAccessUpdatestock_NewsGroupException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update stock_Symbol Exception..
        /// </summary>
        internal static string DataAccessUpdatestock_SymbolException {
            get {
                return ResourceManager.GetString("DataAccessUpdatestock_SymbolException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update stock_SymbolPermLong Exception..
        /// </summary>
        internal static string DataAccessUpdatestock_SymbolPermLongException {
            get {
                return ResourceManager.GetString("DataAccessUpdatestock_SymbolPermLongException", resourceCulture);
            }
        }
    }
}
