//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18213
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vfs.WebCrawler.Business {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Vfs.WebCrawler.Business.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create ApprovedStockNew Exception..
        /// </summary>
        internal static string BusinessCreateApprovedStockNewException {
            get {
                return ResourceManager.GetString("BusinessCreateApprovedStockNewException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create ApprovedStockNew From Reader Exception..
        /// </summary>
        internal static string BusinessCreateApprovedStockNewFromReaderException {
            get {
                return ResourceManager.GetString("BusinessCreateApprovedStockNewFromReaderException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Link Exception..
        /// </summary>
        internal static string BusinessCreateLinkException {
            get {
                return ResourceManager.GetString("BusinessCreateLinkException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Link From Reader Exception..
        /// </summary>
        internal static string BusinessCreateLinkFromReaderException {
            get {
                return ResourceManager.GetString("BusinessCreateLinkFromReaderException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create RejectedStockNew Exception..
        /// </summary>
        internal static string BusinessCreateRejectedStockNewException {
            get {
                return ResourceManager.GetString("BusinessCreateRejectedStockNewException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create RejectedStockNew From Reader Exception..
        /// </summary>
        internal static string BusinessCreateRejectedStockNewFromReaderException {
            get {
                return ResourceManager.GetString("BusinessCreateRejectedStockNewFromReaderException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Source Exception..
        /// </summary>
        internal static string BusinessCreateSourceException {
            get {
                return ResourceManager.GetString("BusinessCreateSourceException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Source From Reader Exception..
        /// </summary>
        internal static string BusinessCreateSourceFromReaderException {
            get {
                return ResourceManager.GetString("BusinessCreateSourceFromReaderException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create StockNew Exception..
        /// </summary>
        internal static string BusinessCreateStockNewException {
            get {
                return ResourceManager.GetString("BusinessCreateStockNewException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create StockNew From Reader Exception..
        /// </summary>
        internal static string BusinessCreateStockNewFromReaderException {
            get {
                return ResourceManager.GetString("BusinessCreateStockNewFromReaderException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create sysdiagram Exception..
        /// </summary>
        internal static string BusinessCreatesysdiagramException {
            get {
                return ResourceManager.GetString("BusinessCreatesysdiagramException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create sysdiagram From Reader Exception..
        /// </summary>
        internal static string BusinessCreatesysdiagramFromReaderException {
            get {
                return ResourceManager.GetString("BusinessCreatesysdiagramFromReaderException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete ApprovedStockNew Exception..
        /// </summary>
        internal static string BusinessDeleteApprovedStockNewException {
            get {
                return ResourceManager.GetString("BusinessDeleteApprovedStockNewException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Link Exception..
        /// </summary>
        internal static string BusinessDeleteLinkException {
            get {
                return ResourceManager.GetString("BusinessDeleteLinkException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete RejectedStockNew Exception..
        /// </summary>
        internal static string BusinessDeleteRejectedStockNewException {
            get {
                return ResourceManager.GetString("BusinessDeleteRejectedStockNewException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Source Exception..
        /// </summary>
        internal static string BusinessDeleteSourceException {
            get {
                return ResourceManager.GetString("BusinessDeleteSourceException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete StockNew Exception..
        /// </summary>
        internal static string BusinessDeleteStockNewException {
            get {
                return ResourceManager.GetString("BusinessDeleteStockNewException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete sysdiagram Exception..
        /// </summary>
        internal static string BusinessDeletesysdiagramException {
            get {
                return ResourceManager.GetString("BusinessDeletesysdiagramException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get ApprovedStockNew Exception..
        /// </summary>
        internal static string BusinessGetApprovedStockNewException {
            get {
                return ResourceManager.GetString("BusinessGetApprovedStockNewException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get ApprovedStockNew List Exception..
        /// </summary>
        internal static string BusinessGetApprovedStockNewListException {
            get {
                return ResourceManager.GetString("BusinessGetApprovedStockNewListException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Link Exception..
        /// </summary>
        internal static string BusinessGetLinkException {
            get {
                return ResourceManager.GetString("BusinessGetLinkException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Link List Exception..
        /// </summary>
        internal static string BusinessGetLinkListException {
            get {
                return ResourceManager.GetString("BusinessGetLinkListException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get RejectedStockNew Exception..
        /// </summary>
        internal static string BusinessGetRejectedStockNewException {
            get {
                return ResourceManager.GetString("BusinessGetRejectedStockNewException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get RejectedStockNew List Exception..
        /// </summary>
        internal static string BusinessGetRejectedStockNewListException {
            get {
                return ResourceManager.GetString("BusinessGetRejectedStockNewListException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Source Exception..
        /// </summary>
        internal static string BusinessGetSourceException {
            get {
                return ResourceManager.GetString("BusinessGetSourceException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Source List Exception..
        /// </summary>
        internal static string BusinessGetSourceListException {
            get {
                return ResourceManager.GetString("BusinessGetSourceListException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get StockNew Exception..
        /// </summary>
        internal static string BusinessGetStockNewException {
            get {
                return ResourceManager.GetString("BusinessGetStockNewException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get StockNew List Exception..
        /// </summary>
        internal static string BusinessGetStockNewListException {
            get {
                return ResourceManager.GetString("BusinessGetStockNewListException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get sysdiagram Exception..
        /// </summary>
        internal static string BusinessGetsysdiagramException {
            get {
                return ResourceManager.GetString("BusinessGetsysdiagramException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get sysdiagram List Exception..
        /// </summary>
        internal static string BusinessGetsysdiagramListException {
            get {
                return ResourceManager.GetString("BusinessGetsysdiagramListException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update ApprovedStockNew Exception..
        /// </summary>
        internal static string BusinessUpdateApprovedStockNewException {
            get {
                return ResourceManager.GetString("BusinessUpdateApprovedStockNewException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Link Exception..
        /// </summary>
        internal static string BusinessUpdateLinkException {
            get {
                return ResourceManager.GetString("BusinessUpdateLinkException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update RejectedStockNew Exception..
        /// </summary>
        internal static string BusinessUpdateRejectedStockNewException {
            get {
                return ResourceManager.GetString("BusinessUpdateRejectedStockNewException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Source Exception..
        /// </summary>
        internal static string BusinessUpdateSourceException {
            get {
                return ResourceManager.GetString("BusinessUpdateSourceException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update StockNew Exception..
        /// </summary>
        internal static string BusinessUpdateStockNewException {
            get {
                return ResourceManager.GetString("BusinessUpdateStockNewException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update sysdiagram Exception..
        /// </summary>
        internal static string BusinessUpdatesysdiagramException {
            get {
                return ResourceManager.GetString("BusinessUpdatesysdiagramException", resourceCulture);
            }
        }
    }
}
