//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18213
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoreSecurityService.Data {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CoreSecurityService.Data.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Customer Exception..
        /// </summary>
        internal static string DataAccessCreateCustomerException {
            get {
                return ResourceManager.GetString("DataAccessCreateCustomerException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Customer From Reader Exception..
        /// </summary>
        internal static string DataAccessCreateCustomerFromReaderException {
            get {
                return ResourceManager.GetString("DataAccessCreateCustomerFromReaderException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create StockPrice Exception..
        /// </summary>
        internal static string DataAccessCreateStockPriceException {
            get {
                return ResourceManager.GetString("DataAccessCreateStockPriceException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create StockPrice From Reader Exception..
        /// </summary>
        internal static string DataAccessCreateStockPriceFromReaderException {
            get {
                return ResourceManager.GetString("DataAccessCreateStockPriceFromReaderException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Customer Exception..
        /// </summary>
        internal static string DataAccessDeleteCustomerException {
            get {
                return ResourceManager.GetString("DataAccessDeleteCustomerException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete StockPrice Exception..
        /// </summary>
        internal static string DataAccessDeleteStockPriceException {
            get {
                return ResourceManager.GetString("DataAccessDeleteStockPriceException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Customer Exception..
        /// </summary>
        internal static string DataAccessGetCustomerException {
            get {
                return ResourceManager.GetString("DataAccessGetCustomerException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Customer List Exception..
        /// </summary>
        internal static string DataAccessGetCustomerListException {
            get {
                return ResourceManager.GetString("DataAccessGetCustomerListException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get StockPrice Exception..
        /// </summary>
        internal static string DataAccessGetStockPriceException {
            get {
                return ResourceManager.GetString("DataAccessGetStockPriceException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get StockPrice List Exception..
        /// </summary>
        internal static string DataAccessGetStockPriceListException {
            get {
                return ResourceManager.GetString("DataAccessGetStockPriceListException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Customer Exception..
        /// </summary>
        internal static string DataAccessUpdateCustomerException {
            get {
                return ResourceManager.GetString("DataAccessUpdateCustomerException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update StockPrice Exception..
        /// </summary>
        internal static string DataAccessUpdateStockPriceException {
            get {
                return ResourceManager.GetString("DataAccessUpdateStockPriceException", resourceCulture);
            }
        }
    }
}
