//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace VfsCustomerService.Business.MTSpam {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Service1Soap", Namespace="http://tempuri.org/")]
    public partial class Service1 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback doSendSimOperationCompleted;
        
        private System.Threading.SendOrPostCallback doSendServiceIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback doSendBrandOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service1() {
            this.Url = global::VfsCustomerService.Business.Properties.Settings.Default.VfsCustomerService_Business_MTSpam_MTSender;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event doSendSimCompletedEventHandler doSendSimCompleted;
        
        /// <remarks/>
        public event doSendServiceIDCompletedEventHandler doSendServiceIDCompleted;
        
        /// <remarks/>
        public event doSendBrandCompletedEventHandler doSendBrandCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/doSendSim", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public long doSendSim(string UserID, string Message, bool TypeURL, string Username, string Password) {
            object[] results = this.Invoke("doSendSim", new object[] {
                        UserID,
                        Message,
                        TypeURL,
                        Username,
                        Password});
            return ((long)(results[0]));
        }
        
        /// <remarks/>
        public void doSendSimAsync(string UserID, string Message, bool TypeURL, string Username, string Password) {
            this.doSendSimAsync(UserID, Message, TypeURL, Username, Password, null);
        }
        
        /// <remarks/>
        public void doSendSimAsync(string UserID, string Message, bool TypeURL, string Username, string Password, object userState) {
            if ((this.doSendSimOperationCompleted == null)) {
                this.doSendSimOperationCompleted = new System.Threading.SendOrPostCallback(this.OndoSendSimOperationCompleted);
            }
            this.InvokeAsync("doSendSim", new object[] {
                        UserID,
                        Message,
                        TypeURL,
                        Username,
                        Password}, this.doSendSimOperationCompleted, userState);
        }
        
        private void OndoSendSimOperationCompleted(object arg) {
            if ((this.doSendSimCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.doSendSimCompleted(this, new doSendSimCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/doSendServiceID", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public long doSendServiceID(string UserID, string Message, string ServiceID, bool TypeURL, string Username, string Password) {
            object[] results = this.Invoke("doSendServiceID", new object[] {
                        UserID,
                        Message,
                        ServiceID,
                        TypeURL,
                        Username,
                        Password});
            return ((long)(results[0]));
        }
        
        /// <remarks/>
        public void doSendServiceIDAsync(string UserID, string Message, string ServiceID, bool TypeURL, string Username, string Password) {
            this.doSendServiceIDAsync(UserID, Message, ServiceID, TypeURL, Username, Password, null);
        }
        
        /// <remarks/>
        public void doSendServiceIDAsync(string UserID, string Message, string ServiceID, bool TypeURL, string Username, string Password, object userState) {
            if ((this.doSendServiceIDOperationCompleted == null)) {
                this.doSendServiceIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OndoSendServiceIDOperationCompleted);
            }
            this.InvokeAsync("doSendServiceID", new object[] {
                        UserID,
                        Message,
                        ServiceID,
                        TypeURL,
                        Username,
                        Password}, this.doSendServiceIDOperationCompleted, userState);
        }
        
        private void OndoSendServiceIDOperationCompleted(object arg) {
            if ((this.doSendServiceIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.doSendServiceIDCompleted(this, new doSendServiceIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/doSendBrand", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public long doSendBrand(string UserID, string Message, string Brand, bool TypeURL, bool RealTime, string Username, string Password) {
            object[] results = this.Invoke("doSendBrand", new object[] {
                        UserID,
                        Message,
                        Brand,
                        TypeURL,
                        RealTime,
                        Username,
                        Password});
            return ((long)(results[0]));
        }
        
        /// <remarks/>
        public void doSendBrandAsync(string UserID, string Message, string Brand, bool TypeURL, bool RealTime, string Username, string Password) {
            this.doSendBrandAsync(UserID, Message, Brand, TypeURL, RealTime, Username, Password, null);
        }
        
        /// <remarks/>
        public void doSendBrandAsync(string UserID, string Message, string Brand, bool TypeURL, bool RealTime, string Username, string Password, object userState) {
            if ((this.doSendBrandOperationCompleted == null)) {
                this.doSendBrandOperationCompleted = new System.Threading.SendOrPostCallback(this.OndoSendBrandOperationCompleted);
            }
            this.InvokeAsync("doSendBrand", new object[] {
                        UserID,
                        Message,
                        Brand,
                        TypeURL,
                        RealTime,
                        Username,
                        Password}, this.doSendBrandOperationCompleted, userState);
        }
        
        private void OndoSendBrandOperationCompleted(object arg) {
            if ((this.doSendBrandCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.doSendBrandCompleted(this, new doSendBrandCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void doSendSimCompletedEventHandler(object sender, doSendSimCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class doSendSimCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal doSendSimCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public long Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((long)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void doSendServiceIDCompletedEventHandler(object sender, doSendServiceIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class doSendServiceIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal doSendServiceIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public long Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((long)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void doSendBrandCompletedEventHandler(object sender, doSendBrandCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class doSendBrandCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal doSendBrandCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public long Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((long)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591