// <auto-generated />
namespace SwipeJob.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class updateuserdateofbirth : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateuserdateofbirth));
        
        string IMigrationMetadata.Id
        {
            get { return "201609070759006_update-user-date-of-birth"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
