//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18213
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vfs.WebCrawler.Data {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Vfs.WebCrawler.Data.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create ApprovedStockNew Exception..
        /// </summary>
        internal static string DataAccessCreateApprovedStockNewException {
            get {
                return ResourceManager.GetString("DataAccessCreateApprovedStockNewException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create ApprovedStockNew From Reader Exception..
        /// </summary>
        internal static string DataAccessCreateApprovedStockNewFromReaderException {
            get {
                return ResourceManager.GetString("DataAccessCreateApprovedStockNewFromReaderException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Link Exception..
        /// </summary>
        internal static string DataAccessCreateLinkException {
            get {
                return ResourceManager.GetString("DataAccessCreateLinkException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Link From Reader Exception..
        /// </summary>
        internal static string DataAccessCreateLinkFromReaderException {
            get {
                return ResourceManager.GetString("DataAccessCreateLinkFromReaderException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create RejectedStockNew Exception..
        /// </summary>
        internal static string DataAccessCreateRejectedStockNewException {
            get {
                return ResourceManager.GetString("DataAccessCreateRejectedStockNewException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create RejectedStockNew From Reader Exception..
        /// </summary>
        internal static string DataAccessCreateRejectedStockNewFromReaderException {
            get {
                return ResourceManager.GetString("DataAccessCreateRejectedStockNewFromReaderException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Source Exception..
        /// </summary>
        internal static string DataAccessCreateSourceException {
            get {
                return ResourceManager.GetString("DataAccessCreateSourceException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Source From Reader Exception..
        /// </summary>
        internal static string DataAccessCreateSourceFromReaderException {
            get {
                return ResourceManager.GetString("DataAccessCreateSourceFromReaderException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create StockNew Exception..
        /// </summary>
        internal static string DataAccessCreateStockNewException {
            get {
                return ResourceManager.GetString("DataAccessCreateStockNewException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create StockNew From Reader Exception..
        /// </summary>
        internal static string DataAccessCreateStockNewFromReaderException {
            get {
                return ResourceManager.GetString("DataAccessCreateStockNewFromReaderException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create sysdiagram Exception..
        /// </summary>
        internal static string DataAccessCreatesysdiagramException {
            get {
                return ResourceManager.GetString("DataAccessCreatesysdiagramException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create sysdiagram From Reader Exception..
        /// </summary>
        internal static string DataAccessCreatesysdiagramFromReaderException {
            get {
                return ResourceManager.GetString("DataAccessCreatesysdiagramFromReaderException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete ApprovedStockNew Exception..
        /// </summary>
        internal static string DataAccessDeleteApprovedStockNewException {
            get {
                return ResourceManager.GetString("DataAccessDeleteApprovedStockNewException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Link Exception..
        /// </summary>
        internal static string DataAccessDeleteLinkException {
            get {
                return ResourceManager.GetString("DataAccessDeleteLinkException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete RejectedStockNew Exception..
        /// </summary>
        internal static string DataAccessDeleteRejectedStockNewException {
            get {
                return ResourceManager.GetString("DataAccessDeleteRejectedStockNewException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Source Exception..
        /// </summary>
        internal static string DataAccessDeleteSourceException {
            get {
                return ResourceManager.GetString("DataAccessDeleteSourceException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete StockNew Exception..
        /// </summary>
        internal static string DataAccessDeleteStockNewException {
            get {
                return ResourceManager.GetString("DataAccessDeleteStockNewException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete sysdiagram Exception..
        /// </summary>
        internal static string DataAccessDeletesysdiagramException {
            get {
                return ResourceManager.GetString("DataAccessDeletesysdiagramException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get ApprovedStockNew Exception..
        /// </summary>
        internal static string DataAccessGetApprovedStockNewException {
            get {
                return ResourceManager.GetString("DataAccessGetApprovedStockNewException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get ApprovedStockNew List Exception..
        /// </summary>
        internal static string DataAccessGetApprovedStockNewListException {
            get {
                return ResourceManager.GetString("DataAccessGetApprovedStockNewListException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Link Exception..
        /// </summary>
        internal static string DataAccessGetLinkException {
            get {
                return ResourceManager.GetString("DataAccessGetLinkException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Link List Exception..
        /// </summary>
        internal static string DataAccessGetLinkListException {
            get {
                return ResourceManager.GetString("DataAccessGetLinkListException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get RejectedStockNew Exception..
        /// </summary>
        internal static string DataAccessGetRejectedStockNewException {
            get {
                return ResourceManager.GetString("DataAccessGetRejectedStockNewException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get RejectedStockNew List Exception..
        /// </summary>
        internal static string DataAccessGetRejectedStockNewListException {
            get {
                return ResourceManager.GetString("DataAccessGetRejectedStockNewListException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Source Exception..
        /// </summary>
        internal static string DataAccessGetSourceException {
            get {
                return ResourceManager.GetString("DataAccessGetSourceException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Source List Exception..
        /// </summary>
        internal static string DataAccessGetSourceListException {
            get {
                return ResourceManager.GetString("DataAccessGetSourceListException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get StockNew Exception..
        /// </summary>
        internal static string DataAccessGetStockNewException {
            get {
                return ResourceManager.GetString("DataAccessGetStockNewException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get StockNew List Exception..
        /// </summary>
        internal static string DataAccessGetStockNewListException {
            get {
                return ResourceManager.GetString("DataAccessGetStockNewListException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get sysdiagram Exception..
        /// </summary>
        internal static string DataAccessGetsysdiagramException {
            get {
                return ResourceManager.GetString("DataAccessGetsysdiagramException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get sysdiagram List Exception..
        /// </summary>
        internal static string DataAccessGetsysdiagramListException {
            get {
                return ResourceManager.GetString("DataAccessGetsysdiagramListException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update ApprovedStockNew Exception..
        /// </summary>
        internal static string DataAccessUpdateApprovedStockNewException {
            get {
                return ResourceManager.GetString("DataAccessUpdateApprovedStockNewException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Link Exception..
        /// </summary>
        internal static string DataAccessUpdateLinkException {
            get {
                return ResourceManager.GetString("DataAccessUpdateLinkException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update RejectedStockNew Exception..
        /// </summary>
        internal static string DataAccessUpdateRejectedStockNewException {
            get {
                return ResourceManager.GetString("DataAccessUpdateRejectedStockNewException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Source Exception..
        /// </summary>
        internal static string DataAccessUpdateSourceException {
            get {
                return ResourceManager.GetString("DataAccessUpdateSourceException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update StockNew Exception..
        /// </summary>
        internal static string DataAccessUpdateStockNewException {
            get {
                return ResourceManager.GetString("DataAccessUpdateStockNewException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update sysdiagram Exception..
        /// </summary>
        internal static string DataAccessUpdatesysdiagramException {
            get {
                return ResourceManager.GetString("DataAccessUpdatesysdiagramException", resourceCulture);
            }
        }
    }
}
