//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18213
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VfsCustomerService.Business {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VfsCustomerService.Business.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create BirthdayMessageLog Exception..
        /// </summary>
        internal static string BusinessCreateBirthdayMessageLogException {
            get {
                return ResourceManager.GetString("BusinessCreateBirthdayMessageLogException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create BirthdayMessageLog From Reader Exception..
        /// </summary>
        internal static string BusinessCreateBirthdayMessageLogFromReaderException {
            get {
                return ResourceManager.GetString("BusinessCreateBirthdayMessageLogFromReaderException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create ContentParameter Exception..
        /// </summary>
        internal static string BusinessCreateContentParameterException {
            get {
                return ResourceManager.GetString("BusinessCreateContentParameterException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create ContentParameter From Reader Exception..
        /// </summary>
        internal static string BusinessCreateContentParameterFromReaderException {
            get {
                return ResourceManager.GetString("BusinessCreateContentParameterFromReaderException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create ContentTemplateAttachement Exception..
        /// </summary>
        internal static string BusinessCreateContentTemplateAttachementException {
            get {
                return ResourceManager.GetString("BusinessCreateContentTemplateAttachementException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create ContentTemplateAttachement From Reader Exception..
        /// </summary>
        internal static string BusinessCreateContentTemplateAttachementFromReaderException {
            get {
                return ResourceManager.GetString("BusinessCreateContentTemplateAttachementFromReaderException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create ContentTemplate Exception..
        /// </summary>
        internal static string BusinessCreateContentTemplateException {
            get {
                return ResourceManager.GetString("BusinessCreateContentTemplateException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create ContentTemplate From Reader Exception..
        /// </summary>
        internal static string BusinessCreateContentTemplateFromReaderException {
            get {
                return ResourceManager.GetString("BusinessCreateContentTemplateFromReaderException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Customer Exception..
        /// </summary>
        internal static string BusinessCreateCustomerException {
            get {
                return ResourceManager.GetString("BusinessCreateCustomerException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Customer From Reader Exception..
        /// </summary>
        internal static string BusinessCreateCustomerFromReaderException {
            get {
                return ResourceManager.GetString("BusinessCreateCustomerFromReaderException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create CustomerType Exception..
        /// </summary>
        internal static string BusinessCreateCustomerTypeException {
            get {
                return ResourceManager.GetString("BusinessCreateCustomerTypeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create CustomerType From Reader Exception..
        /// </summary>
        internal static string BusinessCreateCustomerTypeFromReaderException {
            get {
                return ResourceManager.GetString("BusinessCreateCustomerTypeFromReaderException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create ExtensionMessage Exception..
        /// </summary>
        internal static string BusinessCreateExtensionMessageException {
            get {
                return ResourceManager.GetString("BusinessCreateExtensionMessageException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create ExtensionMessage From Reader Exception..
        /// </summary>
        internal static string BusinessCreateExtensionMessageFromReaderException {
            get {
                return ResourceManager.GetString("BusinessCreateExtensionMessageFromReaderException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create ExtensionMessageLog Exception..
        /// </summary>
        internal static string BusinessCreateExtensionMessageLogException {
            get {
                return ResourceManager.GetString("BusinessCreateExtensionMessageLogException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create ExtensionMessageLog From Reader Exception..
        /// </summary>
        internal static string BusinessCreateExtensionMessageLogFromReaderException {
            get {
                return ResourceManager.GetString("BusinessCreateExtensionMessageLogFromReaderException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create IncomingMessageContent Exception..
        /// </summary>
        internal static string BusinessCreateIncomingMessageContentException {
            get {
                return ResourceManager.GetString("BusinessCreateIncomingMessageContentException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create IncomingMessageContent From Reader Exception..
        /// </summary>
        internal static string BusinessCreateIncomingMessageContentFromReaderException {
            get {
                return ResourceManager.GetString("BusinessCreateIncomingMessageContentFromReaderException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create IncomingMessageContentSent Exception..
        /// </summary>
        internal static string BusinessCreateIncomingMessageContentSentException {
            get {
                return ResourceManager.GetString("BusinessCreateIncomingMessageContentSentException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create IncomingMessageContentSent From Reader Exception..
        /// </summary>
        internal static string BusinessCreateIncomingMessageContentSentFromReaderException {
            get {
                return ResourceManager.GetString("BusinessCreateIncomingMessageContentSentFromReaderException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create MessageCommand Exception..
        /// </summary>
        internal static string BusinessCreateMessageCommandException {
            get {
                return ResourceManager.GetString("BusinessCreateMessageCommandException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create MessageCommand From Reader Exception..
        /// </summary>
        internal static string BusinessCreateMessageCommandFromReaderException {
            get {
                return ResourceManager.GetString("BusinessCreateMessageCommandFromReaderException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create MessageContentAttachement Exception..
        /// </summary>
        internal static string BusinessCreateMessageContentAttachementException {
            get {
                return ResourceManager.GetString("BusinessCreateMessageContentAttachementException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create MessageContentAttachement From Reader Exception..
        /// </summary>
        internal static string BusinessCreateMessageContentAttachementFromReaderException {
            get {
                return ResourceManager.GetString("BusinessCreateMessageContentAttachementFromReaderException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create MessageContent Exception..
        /// </summary>
        internal static string BusinessCreateMessageContentException {
            get {
                return ResourceManager.GetString("BusinessCreateMessageContentException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create MessageContent From Reader Exception..
        /// </summary>
        internal static string BusinessCreateMessageContentFromReaderException {
            get {
                return ResourceManager.GetString("BusinessCreateMessageContentFromReaderException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create MessageContentSentAttachement Exception..
        /// </summary>
        internal static string BusinessCreateMessageContentSentAttachementException {
            get {
                return ResourceManager.GetString("BusinessCreateMessageContentSentAttachementException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create MessageContentSentAttachement From Reader Exception..
        /// </summary>
        internal static string BusinessCreateMessageContentSentAttachementFromReaderException {
            get {
                return ResourceManager.GetString("BusinessCreateMessageContentSentAttachementFromReaderException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create MessageContentSent Exception..
        /// </summary>
        internal static string BusinessCreateMessageContentSentException {
            get {
                return ResourceManager.GetString("BusinessCreateMessageContentSentException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create MessageContentSent From Reader Exception..
        /// </summary>
        internal static string BusinessCreateMessageContentSentFromReaderException {
            get {
                return ResourceManager.GetString("BusinessCreateMessageContentSentFromReaderException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create RelatedMessagelog Exception..
        /// </summary>
        internal static string BusinessCreateRelatedMessagelogException {
            get {
                return ResourceManager.GetString("BusinessCreateRelatedMessagelogException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create RelatedMessagelog From Reader Exception..
        /// </summary>
        internal static string BusinessCreateRelatedMessagelogFromReaderException {
            get {
                return ResourceManager.GetString("BusinessCreateRelatedMessagelogFromReaderException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create ServiceType Exception..
        /// </summary>
        internal static string BusinessCreateServiceTypeException {
            get {
                return ResourceManager.GetString("BusinessCreateServiceTypeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create ServiceType From Reader Exception..
        /// </summary>
        internal static string BusinessCreateServiceTypeFromReaderException {
            get {
                return ResourceManager.GetString("BusinessCreateServiceTypeFromReaderException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete BirthdayMessageLog Exception..
        /// </summary>
        internal static string BusinessDeleteBirthdayMessageLogException {
            get {
                return ResourceManager.GetString("BusinessDeleteBirthdayMessageLogException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete ContentParameter Exception..
        /// </summary>
        internal static string BusinessDeleteContentParameterException {
            get {
                return ResourceManager.GetString("BusinessDeleteContentParameterException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete ContentTemplateAttachement Exception..
        /// </summary>
        internal static string BusinessDeleteContentTemplateAttachementException {
            get {
                return ResourceManager.GetString("BusinessDeleteContentTemplateAttachementException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete ContentTemplate Exception..
        /// </summary>
        internal static string BusinessDeleteContentTemplateException {
            get {
                return ResourceManager.GetString("BusinessDeleteContentTemplateException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Customer Exception..
        /// </summary>
        internal static string BusinessDeleteCustomerException {
            get {
                return ResourceManager.GetString("BusinessDeleteCustomerException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete CustomerType Exception..
        /// </summary>
        internal static string BusinessDeleteCustomerTypeException {
            get {
                return ResourceManager.GetString("BusinessDeleteCustomerTypeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete ExtensionMessage Exception..
        /// </summary>
        internal static string BusinessDeleteExtensionMessageException {
            get {
                return ResourceManager.GetString("BusinessDeleteExtensionMessageException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete ExtensionMessageLog Exception..
        /// </summary>
        internal static string BusinessDeleteExtensionMessageLogException {
            get {
                return ResourceManager.GetString("BusinessDeleteExtensionMessageLogException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete IncomingMessageContent Exception..
        /// </summary>
        internal static string BusinessDeleteIncomingMessageContentException {
            get {
                return ResourceManager.GetString("BusinessDeleteIncomingMessageContentException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete IncomingMessageContentSent Exception..
        /// </summary>
        internal static string BusinessDeleteIncomingMessageContentSentException {
            get {
                return ResourceManager.GetString("BusinessDeleteIncomingMessageContentSentException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete MessageCommand Exception..
        /// </summary>
        internal static string BusinessDeleteMessageCommandException {
            get {
                return ResourceManager.GetString("BusinessDeleteMessageCommandException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete MessageContentAttachement Exception..
        /// </summary>
        internal static string BusinessDeleteMessageContentAttachementException {
            get {
                return ResourceManager.GetString("BusinessDeleteMessageContentAttachementException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete MessageContent Exception..
        /// </summary>
        internal static string BusinessDeleteMessageContentException {
            get {
                return ResourceManager.GetString("BusinessDeleteMessageContentException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete MessageContentSentAttachement Exception..
        /// </summary>
        internal static string BusinessDeleteMessageContentSentAttachementException {
            get {
                return ResourceManager.GetString("BusinessDeleteMessageContentSentAttachementException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete MessageContentSent Exception..
        /// </summary>
        internal static string BusinessDeleteMessageContentSentException {
            get {
                return ResourceManager.GetString("BusinessDeleteMessageContentSentException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete RelatedMessagelog Exception..
        /// </summary>
        internal static string BusinessDeleteRelatedMessagelogException {
            get {
                return ResourceManager.GetString("BusinessDeleteRelatedMessagelogException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete ServiceType Exception..
        /// </summary>
        internal static string BusinessDeleteServiceTypeException {
            get {
                return ResourceManager.GetString("BusinessDeleteServiceTypeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get BirthdayMessageLog Exception..
        /// </summary>
        internal static string BusinessGetBirthdayMessageLogException {
            get {
                return ResourceManager.GetString("BusinessGetBirthdayMessageLogException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get BirthdayMessageLog List Exception..
        /// </summary>
        internal static string BusinessGetBirthdayMessageLogListException {
            get {
                return ResourceManager.GetString("BusinessGetBirthdayMessageLogListException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get ContentParameter Exception..
        /// </summary>
        internal static string BusinessGetContentParameterException {
            get {
                return ResourceManager.GetString("BusinessGetContentParameterException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get ContentParameter List Exception..
        /// </summary>
        internal static string BusinessGetContentParameterListException {
            get {
                return ResourceManager.GetString("BusinessGetContentParameterListException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get ContentTemplateAttachement Exception..
        /// </summary>
        internal static string BusinessGetContentTemplateAttachementException {
            get {
                return ResourceManager.GetString("BusinessGetContentTemplateAttachementException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get ContentTemplateAttachement List Exception..
        /// </summary>
        internal static string BusinessGetContentTemplateAttachementListException {
            get {
                return ResourceManager.GetString("BusinessGetContentTemplateAttachementListException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get ContentTemplate Exception..
        /// </summary>
        internal static string BusinessGetContentTemplateException {
            get {
                return ResourceManager.GetString("BusinessGetContentTemplateException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get ContentTemplate List Exception..
        /// </summary>
        internal static string BusinessGetContentTemplateListException {
            get {
                return ResourceManager.GetString("BusinessGetContentTemplateListException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Customer Exception..
        /// </summary>
        internal static string BusinessGetCustomerException {
            get {
                return ResourceManager.GetString("BusinessGetCustomerException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Customer List Exception..
        /// </summary>
        internal static string BusinessGetCustomerListException {
            get {
                return ResourceManager.GetString("BusinessGetCustomerListException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get CustomerType Exception..
        /// </summary>
        internal static string BusinessGetCustomerTypeException {
            get {
                return ResourceManager.GetString("BusinessGetCustomerTypeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get CustomerType List Exception..
        /// </summary>
        internal static string BusinessGetCustomerTypeListException {
            get {
                return ResourceManager.GetString("BusinessGetCustomerTypeListException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get ExtensionMessage Exception..
        /// </summary>
        internal static string BusinessGetExtensionMessageException {
            get {
                return ResourceManager.GetString("BusinessGetExtensionMessageException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get ExtensionMessage List Exception..
        /// </summary>
        internal static string BusinessGetExtensionMessageListException {
            get {
                return ResourceManager.GetString("BusinessGetExtensionMessageListException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get ExtensionMessageLog Exception..
        /// </summary>
        internal static string BusinessGetExtensionMessageLogException {
            get {
                return ResourceManager.GetString("BusinessGetExtensionMessageLogException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get ExtensionMessageLog List Exception..
        /// </summary>
        internal static string BusinessGetExtensionMessageLogListException {
            get {
                return ResourceManager.GetString("BusinessGetExtensionMessageLogListException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get IncomingMessageContent Exception..
        /// </summary>
        internal static string BusinessGetIncomingMessageContentException {
            get {
                return ResourceManager.GetString("BusinessGetIncomingMessageContentException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get IncomingMessageContent List Exception..
        /// </summary>
        internal static string BusinessGetIncomingMessageContentListException {
            get {
                return ResourceManager.GetString("BusinessGetIncomingMessageContentListException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get IncomingMessageContentSent Exception..
        /// </summary>
        internal static string BusinessGetIncomingMessageContentSentException {
            get {
                return ResourceManager.GetString("BusinessGetIncomingMessageContentSentException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get IncomingMessageContentSent List Exception..
        /// </summary>
        internal static string BusinessGetIncomingMessageContentSentListException {
            get {
                return ResourceManager.GetString("BusinessGetIncomingMessageContentSentListException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get MessageCommand Exception..
        /// </summary>
        internal static string BusinessGetMessageCommandException {
            get {
                return ResourceManager.GetString("BusinessGetMessageCommandException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get MessageCommand List Exception..
        /// </summary>
        internal static string BusinessGetMessageCommandListException {
            get {
                return ResourceManager.GetString("BusinessGetMessageCommandListException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get MessageContentAttachement Exception..
        /// </summary>
        internal static string BusinessGetMessageContentAttachementException {
            get {
                return ResourceManager.GetString("BusinessGetMessageContentAttachementException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get MessageContentAttachement List Exception..
        /// </summary>
        internal static string BusinessGetMessageContentAttachementListException {
            get {
                return ResourceManager.GetString("BusinessGetMessageContentAttachementListException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get MessageContent Exception..
        /// </summary>
        internal static string BusinessGetMessageContentException {
            get {
                return ResourceManager.GetString("BusinessGetMessageContentException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get MessageContent List Exception..
        /// </summary>
        internal static string BusinessGetMessageContentListException {
            get {
                return ResourceManager.GetString("BusinessGetMessageContentListException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get MessageContentSentAttachement Exception..
        /// </summary>
        internal static string BusinessGetMessageContentSentAttachementException {
            get {
                return ResourceManager.GetString("BusinessGetMessageContentSentAttachementException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get MessageContentSentAttachement List Exception..
        /// </summary>
        internal static string BusinessGetMessageContentSentAttachementListException {
            get {
                return ResourceManager.GetString("BusinessGetMessageContentSentAttachementListException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get MessageContentSent Exception..
        /// </summary>
        internal static string BusinessGetMessageContentSentException {
            get {
                return ResourceManager.GetString("BusinessGetMessageContentSentException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get MessageContentSent List Exception..
        /// </summary>
        internal static string BusinessGetMessageContentSentListException {
            get {
                return ResourceManager.GetString("BusinessGetMessageContentSentListException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get RelatedMessagelog Exception..
        /// </summary>
        internal static string BusinessGetRelatedMessagelogException {
            get {
                return ResourceManager.GetString("BusinessGetRelatedMessagelogException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get RelatedMessagelog List Exception..
        /// </summary>
        internal static string BusinessGetRelatedMessagelogListException {
            get {
                return ResourceManager.GetString("BusinessGetRelatedMessagelogListException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get ServiceType Exception..
        /// </summary>
        internal static string BusinessGetServiceTypeException {
            get {
                return ResourceManager.GetString("BusinessGetServiceTypeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get ServiceType List Exception..
        /// </summary>
        internal static string BusinessGetServiceTypeListException {
            get {
                return ResourceManager.GetString("BusinessGetServiceTypeListException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create CreateMessage WithEmail Exception.
        /// </summary>
        internal static string BusinessImport_CreateMessageWithEmailException {
            get {
                return ResourceManager.GetString("BusinessImport_CreateMessageWithEmailException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in sending message to Core Securities.
        /// </summary>
        internal static string BusinessSendSMSToCoreSecuritiesException {
            get {
                return ResourceManager.GetString("BusinessSendSMSToCoreSecuritiesException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update BirthdayMessageLog Exception..
        /// </summary>
        internal static string BusinessUpdateBirthdayMessageLogException {
            get {
                return ResourceManager.GetString("BusinessUpdateBirthdayMessageLogException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update ContentParameter Exception..
        /// </summary>
        internal static string BusinessUpdateContentParameterException {
            get {
                return ResourceManager.GetString("BusinessUpdateContentParameterException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update ContentTemplateAttachement Exception..
        /// </summary>
        internal static string BusinessUpdateContentTemplateAttachementException {
            get {
                return ResourceManager.GetString("BusinessUpdateContentTemplateAttachementException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update ContentTemplate Exception..
        /// </summary>
        internal static string BusinessUpdateContentTemplateException {
            get {
                return ResourceManager.GetString("BusinessUpdateContentTemplateException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Customer Exception..
        /// </summary>
        internal static string BusinessUpdateCustomerException {
            get {
                return ResourceManager.GetString("BusinessUpdateCustomerException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update CustomerType Exception..
        /// </summary>
        internal static string BusinessUpdateCustomerTypeException {
            get {
                return ResourceManager.GetString("BusinessUpdateCustomerTypeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update ExtensionMessage Exception..
        /// </summary>
        internal static string BusinessUpdateExtensionMessageException {
            get {
                return ResourceManager.GetString("BusinessUpdateExtensionMessageException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update ExtensionMessageLog Exception..
        /// </summary>
        internal static string BusinessUpdateExtensionMessageLogException {
            get {
                return ResourceManager.GetString("BusinessUpdateExtensionMessageLogException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update IncomingMessageContent Exception..
        /// </summary>
        internal static string BusinessUpdateIncomingMessageContentException {
            get {
                return ResourceManager.GetString("BusinessUpdateIncomingMessageContentException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update IncomingMessageContentSent Exception..
        /// </summary>
        internal static string BusinessUpdateIncomingMessageContentSentException {
            get {
                return ResourceManager.GetString("BusinessUpdateIncomingMessageContentSentException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update MessageCommand Exception..
        /// </summary>
        internal static string BusinessUpdateMessageCommandException {
            get {
                return ResourceManager.GetString("BusinessUpdateMessageCommandException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update MessageContentAttachement Exception..
        /// </summary>
        internal static string BusinessUpdateMessageContentAttachementException {
            get {
                return ResourceManager.GetString("BusinessUpdateMessageContentAttachementException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update MessageContent Exception..
        /// </summary>
        internal static string BusinessUpdateMessageContentException {
            get {
                return ResourceManager.GetString("BusinessUpdateMessageContentException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update MessageContentSentAttachement Exception..
        /// </summary>
        internal static string BusinessUpdateMessageContentSentAttachementException {
            get {
                return ResourceManager.GetString("BusinessUpdateMessageContentSentAttachementException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update MessageContentSent Exception..
        /// </summary>
        internal static string BusinessUpdateMessageContentSentException {
            get {
                return ResourceManager.GetString("BusinessUpdateMessageContentSentException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update RelatedMessagelog Exception..
        /// </summary>
        internal static string BusinessUpdateRelatedMessagelogException {
            get {
                return ResourceManager.GetString("BusinessUpdateRelatedMessagelogException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update ServiceType Exception..
        /// </summary>
        internal static string BusinessUpdateServiceTypeException {
            get {
                return ResourceManager.GetString("BusinessUpdateServiceTypeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create IncomingMessageContent Exception..
        /// </summary>
        internal static string DataAccessCreateIncomingMessageContentException {
            get {
                return ResourceManager.GetString("DataAccessCreateIncomingMessageContentException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create IncomingMessageContent From Reader Exception..
        /// </summary>
        internal static string DataAccessCreateIncomingMessageContentFromReaderException {
            get {
                return ResourceManager.GetString("DataAccessCreateIncomingMessageContentFromReaderException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create IncomingMessageContentSent Exception..
        /// </summary>
        internal static string DataAccessCreateIncomingMessageContentSentException {
            get {
                return ResourceManager.GetString("DataAccessCreateIncomingMessageContentSentException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create IncomingMessageContentSent From Reader Exception..
        /// </summary>
        internal static string DataAccessCreateIncomingMessageContentSentFromReaderException {
            get {
                return ResourceManager.GetString("DataAccessCreateIncomingMessageContentSentFromReaderException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete IncomingMessageContent Exception..
        /// </summary>
        internal static string DataAccessDeleteIncomingMessageContentException {
            get {
                return ResourceManager.GetString("DataAccessDeleteIncomingMessageContentException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete IncomingMessageContentSent Exception..
        /// </summary>
        internal static string DataAccessDeleteIncomingMessageContentSentException {
            get {
                return ResourceManager.GetString("DataAccessDeleteIncomingMessageContentSentException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get IncomingMessageContent Exception..
        /// </summary>
        internal static string DataAccessGetIncomingMessageContentException {
            get {
                return ResourceManager.GetString("DataAccessGetIncomingMessageContentException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get IncomingMessageContent List Exception..
        /// </summary>
        internal static string DataAccessGetIncomingMessageContentListException {
            get {
                return ResourceManager.GetString("DataAccessGetIncomingMessageContentListException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get IncomingMessageContentSent Exception..
        /// </summary>
        internal static string DataAccessGetIncomingMessageContentSentException {
            get {
                return ResourceManager.GetString("DataAccessGetIncomingMessageContentSentException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get IncomingMessageContentSent List Exception..
        /// </summary>
        internal static string DataAccessGetIncomingMessageContentSentListException {
            get {
                return ResourceManager.GetString("DataAccessGetIncomingMessageContentSentListException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update IncomingMessageContent Exception..
        /// </summary>
        internal static string DataAccessUpdateIncomingMessageContentException {
            get {
                return ResourceManager.GetString("DataAccessUpdateIncomingMessageContentException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update IncomingMessageContentSent Exception..
        /// </summary>
        internal static string DataAccessUpdateIncomingMessageContentSentException {
            get {
                return ResourceManager.GetString("DataAccessUpdateIncomingMessageContentSentException", resourceCulture);
            }
        }
    }
}
