//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhimHang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FrontUser
    {
        public int UserId { get; set; }
        public string UserName { get; set; }
        public string FullName { get; set; }
        public string CardIdentity { get; set; }
        public Nullable<System.DateTime> RegisterDate { get; set; }
        public Nullable<System.DateTime> OpenDate { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public string Password { get; set; }
        public string PINCode { get; set; }
        public byte Type { get; set; }
        public int Retries { get; set; }
        public bool IsFirstLogon { get; set; }
        public Nullable<System.DateTime> LastChangedPassword { get; set; }
        public Nullable<System.DateTime> LastAccess { get; set; }
        public string Ip { get; set; }
        public Nullable<bool> Active { get; set; }
        public int InvestorId { get; set; }
        public Nullable<bool> ActiveTrading { get; set; }
    }
}
