//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhimHang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecommendStock
    {
        public RecommendStock()
        {
            this.Comments = new HashSet<Comment>();
        }
    
        public int ID { get; set; }
        public string StockCode { get; set; }
        public string TYPERecommend { get; set; }
        public Nullable<decimal> BuyPrice { get; set; }
        public Nullable<int> StockHoldingTime { get; set; }
        public Nullable<decimal> TargetSell { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> PostBy { get; set; }
        public Nullable<int> SumComment { get; set; }
        public System.DateTime CreatedModify { get; set; }
        public string ImageUrl { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual UserLogin UserLogin { get; set; }
    }
}
