//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhimHang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class stox_tb_Company
    {
        public int ID { get; set; }
        public string Ticker { get; set; }
        public string ShortName { get; set; }
        public Nullable<short> TypeID { get; set; }
        public string EnglishName { get; set; }
        public string Name { get; set; }
        public string CompanyTypeBeforeListed { get; set; }
        public string IndustryParent { get; set; }
        public string IndustryID { get; set; }
        public string PrimaryProduct { get; set; }
        public Nullable<short> ExchangeID { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string Index { get; set; }
        public string ShareType { get; set; }
        public Nullable<double> ShareCirculate { get; set; }
        public Nullable<System.DateTime> FirstListingDate { get; set; }
        public Nullable<double> ShareIssue { get; set; }
        public Nullable<double> CapitalFund { get; set; }
        public Nullable<double> ParValue { get; set; }
        public Nullable<double> PriceListed { get; set; }
        public string CTCKID { get; set; }
        public Nullable<double> NumberOfCDPT { get; set; }
        public Nullable<double> NumberOfEmployees { get; set; }
        public string WebsiteHomepage { get; set; }
        public string WebsiteCorporateAction { get; set; }
        public string WebsiteAboutCompany { get; set; }
        public string WebsiteInvesterRelation { get; set; }
        public string WebsiteProductServices { get; set; }
        public string WebsiteJobHunter { get; set; }
        public string RegistedOffice { get; set; }
        public string DistrictID { get; set; }
        public string CityID { get; set; }
        public string Telephone_CC { get; set; }
        public string Telephone_AC { get; set; }
        public string Telephone_Number { get; set; }
        public string Fax_CC { get; set; }
        public string Fax_AC { get; set; }
        public string Fax_Number { get; set; }
        public string NumberOfATM { get; set; }
        public string NumberOfSub1 { get; set; }
        public string NumberOfTradeStation { get; set; }
        public string HistoryDev { get; set; }
        public string BusinessStrategies { get; set; }
        public string KeyDevelopments { get; set; }
        public string PosCompany { get; set; }
        public string CompanyProfile { get; set; }
        public string LargeInvestProject { get; set; }
        public string CompanyPromise { get; set; }
        public string BusinessRisk { get; set; }
        public string ePrimaryProduct { get; set; }
        public string eRegistedOffice { get; set; }
        public string eDistrictID { get; set; }
        public string eCityID { get; set; }
        public string eHistoryDev { get; set; }
        public string eBusinessStrategies { get; set; }
        public string eKeyDevelopments { get; set; }
        public string ePosCompany { get; set; }
        public string eCompanyProfile { get; set; }
        public string eLargeInvestProject { get; set; }
        public string eCompanyPromise { get; set; }
        public string eBusinessRisk { get; set; }
        public Nullable<double> freefloat { get; set; }
    }
}
