//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhimHang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class stox_tb_StocksInfo
    {
        public long ID { get; set; }
        public Nullable<int> stock_info_id { get; set; }
        public System.DateTime trading_date { get; set; }
        public string time { get; set; }
        public Nullable<int> stock_id { get; set; }
        public string code { get; set; }
        public byte stock_type { get; set; }
        public Nullable<decimal> total_listing_qtty { get; set; }
        public Nullable<decimal> trading_unit { get; set; }
        public Nullable<byte> listting_status { get; set; }
        public Nullable<decimal> adjust_qtty { get; set; }
        public Nullable<byte> reference_status { get; set; }
        public Nullable<double> adjust_rate { get; set; }
        public Nullable<double> divident_rate { get; set; }
        public Nullable<byte> status { get; set; }
        public Nullable<decimal> total_room { get; set; }
        public Nullable<decimal> current_room { get; set; }
        public Nullable<decimal> basic_price { get; set; }
        public Nullable<decimal> open_price { get; set; }
        public Nullable<decimal> close_price { get; set; }
        public Nullable<decimal> current_price { get; set; }
        public Nullable<decimal> current_qtty { get; set; }
        public Nullable<decimal> highest_price { get; set; }
        public Nullable<decimal> lowest_price { get; set; }
        public Nullable<decimal> best_offer_price { get; set; }
        public Nullable<decimal> best_bid_price { get; set; }
        public Nullable<decimal> ceiling_price { get; set; }
        public Nullable<decimal> floor_price { get; set; }
        public Nullable<decimal> total_offer_qtty { get; set; }
        public Nullable<decimal> total_bid_qtty { get; set; }
        public Nullable<decimal> best_offer_qtty { get; set; }
        public Nullable<decimal> best_bid_qtty { get; set; }
        public Nullable<decimal> prior_price { get; set; }
        public Nullable<decimal> prior_close_price { get; set; }
        public Nullable<decimal> match_price { get; set; }
        public Nullable<decimal> match_qtty { get; set; }
        public Nullable<byte> deleted { get; set; }
        public Nullable<System.DateTime> date_created { get; set; }
        public Nullable<System.DateTime> date_modified { get; set; }
        public string modified_by { get; set; }
        public string created_by { get; set; }
        public string name { get; set; }
        public Nullable<int> parvalue { get; set; }
        public Nullable<int> floor_code { get; set; }
        public Nullable<decimal> match_value { get; set; }
        public Nullable<byte> is_calcindex { get; set; }
        public Nullable<byte> is_determinecl { get; set; }
        public Nullable<int> date_no { get; set; }
        public Nullable<int> offer_count { get; set; }
        public Nullable<int> bid_count { get; set; }
        public Nullable<decimal> average_price { get; set; }
        public Nullable<decimal> index_price { get; set; }
        public Nullable<decimal> prev_prior_price { get; set; }
        public Nullable<decimal> yieldmat { get; set; }
        public Nullable<decimal> prev_prior_close_price { get; set; }
        public Nullable<decimal> nm_total_traded_qtty { get; set; }
        public Nullable<decimal> nm_total_traded_value { get; set; }
        public Nullable<decimal> pt_match_qtty { get; set; }
        public Nullable<decimal> pt_match_price { get; set; }
        public Nullable<decimal> pt_total_traded_qtty { get; set; }
        public Nullable<decimal> pt_total_traded_value { get; set; }
        public Nullable<decimal> total_buy_trading_qtty { get; set; }
        public Nullable<int> buy_count { get; set; }
        public Nullable<decimal> total_buy_trading_value { get; set; }
        public Nullable<decimal> total_sell_trading_qtty { get; set; }
        public Nullable<int> sell_count { get; set; }
        public Nullable<decimal> total_sell_trading_value { get; set; }
        public Nullable<decimal> total_trading_qtty { get; set; }
        public Nullable<decimal> total_trading_value { get; set; }
        public Nullable<decimal> buy_foreign_qtty { get; set; }
        public Nullable<decimal> buy_foreign_value { get; set; }
        public Nullable<decimal> sell_foreign_qtty { get; set; }
        public Nullable<decimal> sell_foreign_value { get; set; }
        public Nullable<decimal> remain_foreign_qtty { get; set; }
        public Nullable<decimal> pt_yieldmat { get; set; }
        public Nullable<System.DateTime> dateReport { get; set; }
        public Nullable<double> ClosePrice_Adjusted { get; set; }
        public Nullable<double> Rate_Adjusted { get; set; }
        public Nullable<double> Highest_Adjusted { get; set; }
        public Nullable<double> Lowest_Adjusted { get; set; }
        public Nullable<double> OpenPrice_Adjusted { get; set; }
    }
}
