//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAOvEntitiesFramwork_CusServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report
    {
        public long Id { get; set; }
        public string Title { get; set; }
        public string UploadDir { get; set; }
        public Nullable<System.DateTime> DateViewCustomer { get; set; }
        public Nullable<long> TotalDownload { get; set; }
        public Nullable<long> FileSize { get; set; }
        public Nullable<int> IdReportType { get; set; }
        public string Ticker { get; set; }
        public System.DateTime CreateDate { get; set; }
    
        public virtual ReportType ReportType { get; set; }
    }
}
