//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18213
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoreSecurityService.Business {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CoreSecurityService.Business.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Customer Exception..
        /// </summary>
        internal static string BusinessCreateCustomerException {
            get {
                return ResourceManager.GetString("BusinessCreateCustomerException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Customer From Reader Exception..
        /// </summary>
        internal static string BusinessCreateCustomerFromReaderException {
            get {
                return ResourceManager.GetString("BusinessCreateCustomerFromReaderException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create StockPrice Exception..
        /// </summary>
        internal static string BusinessCreateStockPriceException {
            get {
                return ResourceManager.GetString("BusinessCreateStockPriceException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create StockPrice From Reader Exception..
        /// </summary>
        internal static string BusinessCreateStockPriceFromReaderException {
            get {
                return ResourceManager.GetString("BusinessCreateStockPriceFromReaderException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Customer Exception..
        /// </summary>
        internal static string BusinessDeleteCustomerException {
            get {
                return ResourceManager.GetString("BusinessDeleteCustomerException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete StockPrice Exception..
        /// </summary>
        internal static string BusinessDeleteStockPriceException {
            get {
                return ResourceManager.GetString("BusinessDeleteStockPriceException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Customer Exception..
        /// </summary>
        internal static string BusinessGetCustomerException {
            get {
                return ResourceManager.GetString("BusinessGetCustomerException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Customer List Exception..
        /// </summary>
        internal static string BusinessGetCustomerListException {
            get {
                return ResourceManager.GetString("BusinessGetCustomerListException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get StockPrice Exception..
        /// </summary>
        internal static string BusinessGetStockPriceException {
            get {
                return ResourceManager.GetString("BusinessGetStockPriceException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get StockPrice List Exception..
        /// </summary>
        internal static string BusinessGetStockPriceListException {
            get {
                return ResourceManager.GetString("BusinessGetStockPriceListException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Customer Exception..
        /// </summary>
        internal static string BusinessUpdateCustomerException {
            get {
                return ResourceManager.GetString("BusinessUpdateCustomerException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update StockPrice Exception..
        /// </summary>
        internal static string BusinessUpdateStockPriceException {
            get {
                return ResourceManager.GetString("BusinessUpdateStockPriceException", resourceCulture);
            }
        }
    }
}
