//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18213
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18213.
// 
#pragma warning disable 1591

namespace VfsCustomerService.Business.CoreSecuritiesSms {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18213")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="MOReceiverHttpBinding", Namespace="http://ws.sms.gateway.vssd.com")]
    public partial class MOReceiver : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback messageReceiverOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public MOReceiver() {
            this.Url = global::VfsCustomerService.Business.Properties.Settings.Default.VfsCustomerService_Business_CoreSecuritiesSms_MOReceiver;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event messageReceiverCompletedEventHandler messageReceiverCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("inquireout", Namespace="http://ws.sms.gateway.vssd.com")]
        public string messageReceiver([System.Xml.Serialization.XmlElementAttribute(Namespace="http://ws.sms.gateway.vssd.com")] string UserID, [System.Xml.Serialization.XmlElementAttribute(Namespace="http://ws.sms.gateway.vssd.com")] string ServiceID, [System.Xml.Serialization.XmlElementAttribute(Namespace="http://ws.sms.gateway.vssd.com")] string CommandCode, [System.Xml.Serialization.XmlElementAttribute(Namespace="http://ws.sms.gateway.vssd.com")] string Message, [System.Xml.Serialization.XmlElementAttribute(Namespace="http://ws.sms.gateway.vssd.com")] string RequestID, [System.Xml.Serialization.XmlElementAttribute(Namespace="http://ws.sms.gateway.vssd.com")] string MoID, [System.Xml.Serialization.XmlElementAttribute(Namespace="http://ws.sms.gateway.vssd.com")] string Username, [System.Xml.Serialization.XmlElementAttribute(Namespace="http://ws.sms.gateway.vssd.com")] string Password) {
            object[] results = this.Invoke("messageReceiver", new object[] {
                        UserID,
                        ServiceID,
                        CommandCode,
                        Message,
                        RequestID,
                        MoID,
                        Username,
                        Password});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void messageReceiverAsync(string UserID, string ServiceID, string CommandCode, string Message, string RequestID, string MoID, string Username, string Password) {
            this.messageReceiverAsync(UserID, ServiceID, CommandCode, Message, RequestID, MoID, Username, Password, null);
        }
        
        /// <remarks/>
        public void messageReceiverAsync(string UserID, string ServiceID, string CommandCode, string Message, string RequestID, string MoID, string Username, string Password, object userState) {
            if ((this.messageReceiverOperationCompleted == null)) {
                this.messageReceiverOperationCompleted = new System.Threading.SendOrPostCallback(this.OnmessageReceiverOperationCompleted);
            }
            this.InvokeAsync("messageReceiver", new object[] {
                        UserID,
                        ServiceID,
                        CommandCode,
                        Message,
                        RequestID,
                        MoID,
                        Username,
                        Password}, this.messageReceiverOperationCompleted, userState);
        }
        
        private void OnmessageReceiverOperationCompleted(object arg) {
            if ((this.messageReceiverCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.messageReceiverCompleted(this, new messageReceiverCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18213")]
    public delegate void messageReceiverCompletedEventHandler(object sender, messageReceiverCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18213")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class messageReceiverCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal messageReceiverCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591