//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18213
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VfsCustomerService.Data {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VfsCustomerService.Data.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create BirthdayMessageLog Exception..
        /// </summary>
        internal static string DataAccessCreateBirthdayMessageLogException {
            get {
                return ResourceManager.GetString("DataAccessCreateBirthdayMessageLogException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create BirthdayMessageLog From Reader Exception..
        /// </summary>
        internal static string DataAccessCreateBirthdayMessageLogFromReaderException {
            get {
                return ResourceManager.GetString("DataAccessCreateBirthdayMessageLogFromReaderException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create ContentParameter Exception..
        /// </summary>
        internal static string DataAccessCreateContentParameterException {
            get {
                return ResourceManager.GetString("DataAccessCreateContentParameterException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create ContentParameter Exception..
        /// </summary>
        internal static string DataAccessCreateContentParameterException1 {
            get {
                return ResourceManager.GetString("DataAccessCreateContentParameterException1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create ContentParameter From Reader Exception..
        /// </summary>
        internal static string DataAccessCreateContentParameterFromReaderException {
            get {
                return ResourceManager.GetString("DataAccessCreateContentParameterFromReaderException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create ContentParameter From Reader Exception..
        /// </summary>
        internal static string DataAccessCreateContentParameterFromReaderException1 {
            get {
                return ResourceManager.GetString("DataAccessCreateContentParameterFromReaderException1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create ContentTemplateAttachement Exception..
        /// </summary>
        internal static string DataAccessCreateContentTemplateAttachementException {
            get {
                return ResourceManager.GetString("DataAccessCreateContentTemplateAttachementException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create ContentTemplateAttachement From Reader Exception..
        /// </summary>
        internal static string DataAccessCreateContentTemplateAttachementFromReaderException {
            get {
                return ResourceManager.GetString("DataAccessCreateContentTemplateAttachementFromReaderException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create ContentTemplate Exception..
        /// </summary>
        internal static string DataAccessCreateContentTemplateException {
            get {
                return ResourceManager.GetString("DataAccessCreateContentTemplateException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create ContentTemplate Exception..
        /// </summary>
        internal static string DataAccessCreateContentTemplateException1 {
            get {
                return ResourceManager.GetString("DataAccessCreateContentTemplateException1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create ContentTemplate From Reader Exception..
        /// </summary>
        internal static string DataAccessCreateContentTemplateFromReaderException {
            get {
                return ResourceManager.GetString("DataAccessCreateContentTemplateFromReaderException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create ContentTemplate From Reader Exception..
        /// </summary>
        internal static string DataAccessCreateContentTemplateFromReaderException1 {
            get {
                return ResourceManager.GetString("DataAccessCreateContentTemplateFromReaderException1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Customer Exception..
        /// </summary>
        internal static string DataAccessCreateCustomerException {
            get {
                return ResourceManager.GetString("DataAccessCreateCustomerException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Customer From Reader Exception..
        /// </summary>
        internal static string DataAccessCreateCustomerFromReaderException {
            get {
                return ResourceManager.GetString("DataAccessCreateCustomerFromReaderException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create CustomerType Exception..
        /// </summary>
        internal static string DataAccessCreateCustomerTypeException {
            get {
                return ResourceManager.GetString("DataAccessCreateCustomerTypeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create CustomerType From Reader Exception..
        /// </summary>
        internal static string DataAccessCreateCustomerTypeFromReaderException {
            get {
                return ResourceManager.GetString("DataAccessCreateCustomerTypeFromReaderException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create ExtensionMessage Exception..
        /// </summary>
        internal static string DataAccessCreateExtensionMessageException {
            get {
                return ResourceManager.GetString("DataAccessCreateExtensionMessageException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create ExtensionMessage From Reader Exception..
        /// </summary>
        internal static string DataAccessCreateExtensionMessageFromReaderException {
            get {
                return ResourceManager.GetString("DataAccessCreateExtensionMessageFromReaderException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create ExtensionMessageLog Exception..
        /// </summary>
        internal static string DataAccessCreateExtensionMessageLogException {
            get {
                return ResourceManager.GetString("DataAccessCreateExtensionMessageLogException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create ExtensionMessageLog From Reader Exception..
        /// </summary>
        internal static string DataAccessCreateExtensionMessageLogFromReaderException {
            get {
                return ResourceManager.GetString("DataAccessCreateExtensionMessageLogFromReaderException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create IncomingMessageContent Exception..
        /// </summary>
        internal static string DataAccessCreateIncomingMessageContentException {
            get {
                return ResourceManager.GetString("DataAccessCreateIncomingMessageContentException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create IncomingMessageContent From Reader Exception..
        /// </summary>
        internal static string DataAccessCreateIncomingMessageContentFromReaderException {
            get {
                return ResourceManager.GetString("DataAccessCreateIncomingMessageContentFromReaderException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create IncomingMessageContentSent Exception..
        /// </summary>
        internal static string DataAccessCreateIncomingMessageContentSentException {
            get {
                return ResourceManager.GetString("DataAccessCreateIncomingMessageContentSentException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create IncomingMessageContentSent From Reader Exception..
        /// </summary>
        internal static string DataAccessCreateIncomingMessageContentSentFromReaderException {
            get {
                return ResourceManager.GetString("DataAccessCreateIncomingMessageContentSentFromReaderException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create MessageCommand Exception..
        /// </summary>
        internal static string DataAccessCreateMessageCommandException {
            get {
                return ResourceManager.GetString("DataAccessCreateMessageCommandException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create MessageCommand Exception..
        /// </summary>
        internal static string DataAccessCreateMessageCommandException1 {
            get {
                return ResourceManager.GetString("DataAccessCreateMessageCommandException1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create MessageCommand From Reader Exception..
        /// </summary>
        internal static string DataAccessCreateMessageCommandFromReaderException {
            get {
                return ResourceManager.GetString("DataAccessCreateMessageCommandFromReaderException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create MessageCommand From Reader Exception..
        /// </summary>
        internal static string DataAccessCreateMessageCommandFromReaderException1 {
            get {
                return ResourceManager.GetString("DataAccessCreateMessageCommandFromReaderException1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create MessageContentAttachement Exception..
        /// </summary>
        internal static string DataAccessCreateMessageContentAttachementException {
            get {
                return ResourceManager.GetString("DataAccessCreateMessageContentAttachementException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create MessageContentAttachement From Reader Exception..
        /// </summary>
        internal static string DataAccessCreateMessageContentAttachementFromReaderException {
            get {
                return ResourceManager.GetString("DataAccessCreateMessageContentAttachementFromReaderException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create MessageContent Exception..
        /// </summary>
        internal static string DataAccessCreateMessageContentException {
            get {
                return ResourceManager.GetString("DataAccessCreateMessageContentException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create MessageContent Exception..
        /// </summary>
        internal static string DataAccessCreateMessageContentException1 {
            get {
                return ResourceManager.GetString("DataAccessCreateMessageContentException1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create MessageContent From Reader Exception..
        /// </summary>
        internal static string DataAccessCreateMessageContentFromReaderException {
            get {
                return ResourceManager.GetString("DataAccessCreateMessageContentFromReaderException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create MessageContent From Reader Exception..
        /// </summary>
        internal static string DataAccessCreateMessageContentFromReaderException1 {
            get {
                return ResourceManager.GetString("DataAccessCreateMessageContentFromReaderException1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create MessageContentSentAttachement Exception..
        /// </summary>
        internal static string DataAccessCreateMessageContentSentAttachementException {
            get {
                return ResourceManager.GetString("DataAccessCreateMessageContentSentAttachementException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create MessageContentSentAttachement From Reader Exception..
        /// </summary>
        internal static string DataAccessCreateMessageContentSentAttachementFromReaderException {
            get {
                return ResourceManager.GetString("DataAccessCreateMessageContentSentAttachementFromReaderException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create MessageContentSent Exception..
        /// </summary>
        internal static string DataAccessCreateMessageContentSentException {
            get {
                return ResourceManager.GetString("DataAccessCreateMessageContentSentException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create MessageContentSent Exception..
        /// </summary>
        internal static string DataAccessCreateMessageContentSentException1 {
            get {
                return ResourceManager.GetString("DataAccessCreateMessageContentSentException1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create MessageContentSent From Reader Exception..
        /// </summary>
        internal static string DataAccessCreateMessageContentSentFromReaderException {
            get {
                return ResourceManager.GetString("DataAccessCreateMessageContentSentFromReaderException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create MessageContentSent From Reader Exception..
        /// </summary>
        internal static string DataAccessCreateMessageContentSentFromReaderException1 {
            get {
                return ResourceManager.GetString("DataAccessCreateMessageContentSentFromReaderException1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create RelatedMessagelog Exception..
        /// </summary>
        internal static string DataAccessCreateRelatedMessagelogException {
            get {
                return ResourceManager.GetString("DataAccessCreateRelatedMessagelogException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create RelatedMessagelog From Reader Exception..
        /// </summary>
        internal static string DataAccessCreateRelatedMessagelogFromReaderException {
            get {
                return ResourceManager.GetString("DataAccessCreateRelatedMessagelogFromReaderException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create ServiceType Exception..
        /// </summary>
        internal static string DataAccessCreateServiceTypeException {
            get {
                return ResourceManager.GetString("DataAccessCreateServiceTypeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create ServiceType Exception..
        /// </summary>
        internal static string DataAccessCreateServiceTypeException1 {
            get {
                return ResourceManager.GetString("DataAccessCreateServiceTypeException1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create ServiceType From Reader Exception..
        /// </summary>
        internal static string DataAccessCreateServiceTypeFromReaderException {
            get {
                return ResourceManager.GetString("DataAccessCreateServiceTypeFromReaderException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create ServiceType From Reader Exception..
        /// </summary>
        internal static string DataAccessCreateServiceTypeFromReaderException1 {
            get {
                return ResourceManager.GetString("DataAccessCreateServiceTypeFromReaderException1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete BirthdayMessageLog Exception..
        /// </summary>
        internal static string DataAccessDeleteBirthdayMessageLogException {
            get {
                return ResourceManager.GetString("DataAccessDeleteBirthdayMessageLogException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete ContentParameter Exception..
        /// </summary>
        internal static string DataAccessDeleteContentParameterException {
            get {
                return ResourceManager.GetString("DataAccessDeleteContentParameterException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete ContentParameter Exception..
        /// </summary>
        internal static string DataAccessDeleteContentParameterException1 {
            get {
                return ResourceManager.GetString("DataAccessDeleteContentParameterException1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete ContentTemplateAttachement Exception..
        /// </summary>
        internal static string DataAccessDeleteContentTemplateAttachementException {
            get {
                return ResourceManager.GetString("DataAccessDeleteContentTemplateAttachementException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete ContentTemplate Exception..
        /// </summary>
        internal static string DataAccessDeleteContentTemplateException {
            get {
                return ResourceManager.GetString("DataAccessDeleteContentTemplateException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete ContentTemplate Exception..
        /// </summary>
        internal static string DataAccessDeleteContentTemplateException1 {
            get {
                return ResourceManager.GetString("DataAccessDeleteContentTemplateException1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Customer Exception..
        /// </summary>
        internal static string DataAccessDeleteCustomerException {
            get {
                return ResourceManager.GetString("DataAccessDeleteCustomerException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete CustomerType Exception..
        /// </summary>
        internal static string DataAccessDeleteCustomerTypeException {
            get {
                return ResourceManager.GetString("DataAccessDeleteCustomerTypeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete ExtensionMessage Exception..
        /// </summary>
        internal static string DataAccessDeleteExtensionMessageException {
            get {
                return ResourceManager.GetString("DataAccessDeleteExtensionMessageException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete ExtensionMessageLog Exception..
        /// </summary>
        internal static string DataAccessDeleteExtensionMessageLogException {
            get {
                return ResourceManager.GetString("DataAccessDeleteExtensionMessageLogException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete IncomingMessageContent Exception..
        /// </summary>
        internal static string DataAccessDeleteIncomingMessageContentException {
            get {
                return ResourceManager.GetString("DataAccessDeleteIncomingMessageContentException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete IncomingMessageContentSent Exception..
        /// </summary>
        internal static string DataAccessDeleteIncomingMessageContentSentException {
            get {
                return ResourceManager.GetString("DataAccessDeleteIncomingMessageContentSentException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete MessageCommand Exception..
        /// </summary>
        internal static string DataAccessDeleteMessageCommandException {
            get {
                return ResourceManager.GetString("DataAccessDeleteMessageCommandException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete MessageCommand Exception..
        /// </summary>
        internal static string DataAccessDeleteMessageCommandException1 {
            get {
                return ResourceManager.GetString("DataAccessDeleteMessageCommandException1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete MessageContentAttachement Exception..
        /// </summary>
        internal static string DataAccessDeleteMessageContentAttachementException {
            get {
                return ResourceManager.GetString("DataAccessDeleteMessageContentAttachementException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete MessageContent Exception..
        /// </summary>
        internal static string DataAccessDeleteMessageContentException {
            get {
                return ResourceManager.GetString("DataAccessDeleteMessageContentException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete MessageContent Exception..
        /// </summary>
        internal static string DataAccessDeleteMessageContentException1 {
            get {
                return ResourceManager.GetString("DataAccessDeleteMessageContentException1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete MessageContentSentAttachement Exception..
        /// </summary>
        internal static string DataAccessDeleteMessageContentSentAttachementException {
            get {
                return ResourceManager.GetString("DataAccessDeleteMessageContentSentAttachementException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete MessageContentSent Exception..
        /// </summary>
        internal static string DataAccessDeleteMessageContentSentException {
            get {
                return ResourceManager.GetString("DataAccessDeleteMessageContentSentException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete MessageContentSent Exception..
        /// </summary>
        internal static string DataAccessDeleteMessageContentSentException1 {
            get {
                return ResourceManager.GetString("DataAccessDeleteMessageContentSentException1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete RelatedMessagelog Exception..
        /// </summary>
        internal static string DataAccessDeleteRelatedMessagelogException {
            get {
                return ResourceManager.GetString("DataAccessDeleteRelatedMessagelogException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete ServiceType Exception..
        /// </summary>
        internal static string DataAccessDeleteServiceTypeException {
            get {
                return ResourceManager.GetString("DataAccessDeleteServiceTypeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete ServiceType Exception..
        /// </summary>
        internal static string DataAccessDeleteServiceTypeException1 {
            get {
                return ResourceManager.GetString("DataAccessDeleteServiceTypeException1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get BirthdayMessageLog Exception..
        /// </summary>
        internal static string DataAccessGetBirthdayMessageLogException {
            get {
                return ResourceManager.GetString("DataAccessGetBirthdayMessageLogException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get BirthdayMessageLog List Exception..
        /// </summary>
        internal static string DataAccessGetBirthdayMessageLogListException {
            get {
                return ResourceManager.GetString("DataAccessGetBirthdayMessageLogListException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get ContentParameter Exception..
        /// </summary>
        internal static string DataAccessGetContentParameterException {
            get {
                return ResourceManager.GetString("DataAccessGetContentParameterException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get ContentParameter Exception..
        /// </summary>
        internal static string DataAccessGetContentParameterException1 {
            get {
                return ResourceManager.GetString("DataAccessGetContentParameterException1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get ContentParameter List Exception..
        /// </summary>
        internal static string DataAccessGetContentParameterListException {
            get {
                return ResourceManager.GetString("DataAccessGetContentParameterListException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get ContentParameter List Exception..
        /// </summary>
        internal static string DataAccessGetContentParameterListException1 {
            get {
                return ResourceManager.GetString("DataAccessGetContentParameterListException1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get ContentTemplateAttachement Exception..
        /// </summary>
        internal static string DataAccessGetContentTemplateAttachementException {
            get {
                return ResourceManager.GetString("DataAccessGetContentTemplateAttachementException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get ContentTemplateAttachement List Exception..
        /// </summary>
        internal static string DataAccessGetContentTemplateAttachementListException {
            get {
                return ResourceManager.GetString("DataAccessGetContentTemplateAttachementListException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get ContentTemplate Exception..
        /// </summary>
        internal static string DataAccessGetContentTemplateException {
            get {
                return ResourceManager.GetString("DataAccessGetContentTemplateException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get ContentTemplate Exception..
        /// </summary>
        internal static string DataAccessGetContentTemplateException1 {
            get {
                return ResourceManager.GetString("DataAccessGetContentTemplateException1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get ContentTemplate List Exception..
        /// </summary>
        internal static string DataAccessGetContentTemplateListException {
            get {
                return ResourceManager.GetString("DataAccessGetContentTemplateListException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get ContentTemplate List Exception..
        /// </summary>
        internal static string DataAccessGetContentTemplateListException1 {
            get {
                return ResourceManager.GetString("DataAccessGetContentTemplateListException1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Customer Exception..
        /// </summary>
        internal static string DataAccessGetCustomerException {
            get {
                return ResourceManager.GetString("DataAccessGetCustomerException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Customer List Exception..
        /// </summary>
        internal static string DataAccessGetCustomerListException {
            get {
                return ResourceManager.GetString("DataAccessGetCustomerListException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get CustomerType Exception..
        /// </summary>
        internal static string DataAccessGetCustomerTypeException {
            get {
                return ResourceManager.GetString("DataAccessGetCustomerTypeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get CustomerType List Exception..
        /// </summary>
        internal static string DataAccessGetCustomerTypeListException {
            get {
                return ResourceManager.GetString("DataAccessGetCustomerTypeListException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get ExtensionMessage Exception..
        /// </summary>
        internal static string DataAccessGetExtensionMessageException {
            get {
                return ResourceManager.GetString("DataAccessGetExtensionMessageException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get ExtensionMessage List Exception..
        /// </summary>
        internal static string DataAccessGetExtensionMessageListException {
            get {
                return ResourceManager.GetString("DataAccessGetExtensionMessageListException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get ExtensionMessageLog Exception..
        /// </summary>
        internal static string DataAccessGetExtensionMessageLogException {
            get {
                return ResourceManager.GetString("DataAccessGetExtensionMessageLogException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get ExtensionMessageLog List Exception..
        /// </summary>
        internal static string DataAccessGetExtensionMessageLogListException {
            get {
                return ResourceManager.GetString("DataAccessGetExtensionMessageLogListException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get IncomingMessageContent Exception..
        /// </summary>
        internal static string DataAccessGetIncomingMessageContentException {
            get {
                return ResourceManager.GetString("DataAccessGetIncomingMessageContentException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get IncomingMessageContent List Exception..
        /// </summary>
        internal static string DataAccessGetIncomingMessageContentListException {
            get {
                return ResourceManager.GetString("DataAccessGetIncomingMessageContentListException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get IncomingMessageContentSent Exception..
        /// </summary>
        internal static string DataAccessGetIncomingMessageContentSentException {
            get {
                return ResourceManager.GetString("DataAccessGetIncomingMessageContentSentException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get IncomingMessageContentSent List Exception..
        /// </summary>
        internal static string DataAccessGetIncomingMessageContentSentListException {
            get {
                return ResourceManager.GetString("DataAccessGetIncomingMessageContentSentListException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get MessageCommand Exception..
        /// </summary>
        internal static string DataAccessGetMessageCommandException {
            get {
                return ResourceManager.GetString("DataAccessGetMessageCommandException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get MessageCommand Exception..
        /// </summary>
        internal static string DataAccessGetMessageCommandException1 {
            get {
                return ResourceManager.GetString("DataAccessGetMessageCommandException1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get MessageCommand List Exception..
        /// </summary>
        internal static string DataAccessGetMessageCommandListException {
            get {
                return ResourceManager.GetString("DataAccessGetMessageCommandListException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get MessageCommand List Exception..
        /// </summary>
        internal static string DataAccessGetMessageCommandListException1 {
            get {
                return ResourceManager.GetString("DataAccessGetMessageCommandListException1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get MessageContentAttachement Exception..
        /// </summary>
        internal static string DataAccessGetMessageContentAttachementException {
            get {
                return ResourceManager.GetString("DataAccessGetMessageContentAttachementException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get MessageContentAttachement List Exception..
        /// </summary>
        internal static string DataAccessGetMessageContentAttachementListException {
            get {
                return ResourceManager.GetString("DataAccessGetMessageContentAttachementListException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get MessageContent Exception..
        /// </summary>
        internal static string DataAccessGetMessageContentException {
            get {
                return ResourceManager.GetString("DataAccessGetMessageContentException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get MessageContent Exception..
        /// </summary>
        internal static string DataAccessGetMessageContentException1 {
            get {
                return ResourceManager.GetString("DataAccessGetMessageContentException1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get MessageContent List Exception..
        /// </summary>
        internal static string DataAccessGetMessageContentListException {
            get {
                return ResourceManager.GetString("DataAccessGetMessageContentListException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get MessageContent List Exception..
        /// </summary>
        internal static string DataAccessGetMessageContentListException1 {
            get {
                return ResourceManager.GetString("DataAccessGetMessageContentListException1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get MessageContentSentAttachement Exception..
        /// </summary>
        internal static string DataAccessGetMessageContentSentAttachementException {
            get {
                return ResourceManager.GetString("DataAccessGetMessageContentSentAttachementException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get MessageContentSentAttachement List Exception..
        /// </summary>
        internal static string DataAccessGetMessageContentSentAttachementListException {
            get {
                return ResourceManager.GetString("DataAccessGetMessageContentSentAttachementListException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get MessageContentSent Exception..
        /// </summary>
        internal static string DataAccessGetMessageContentSentException {
            get {
                return ResourceManager.GetString("DataAccessGetMessageContentSentException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get MessageContentSent Exception..
        /// </summary>
        internal static string DataAccessGetMessageContentSentException1 {
            get {
                return ResourceManager.GetString("DataAccessGetMessageContentSentException1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get MessageContentSent List Exception..
        /// </summary>
        internal static string DataAccessGetMessageContentSentListException {
            get {
                return ResourceManager.GetString("DataAccessGetMessageContentSentListException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get MessageContentSent List Exception..
        /// </summary>
        internal static string DataAccessGetMessageContentSentListException1 {
            get {
                return ResourceManager.GetString("DataAccessGetMessageContentSentListException1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get RelatedMessagelog Exception..
        /// </summary>
        internal static string DataAccessGetRelatedMessagelogException {
            get {
                return ResourceManager.GetString("DataAccessGetRelatedMessagelogException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get RelatedMessagelog List Exception..
        /// </summary>
        internal static string DataAccessGetRelatedMessagelogListException {
            get {
                return ResourceManager.GetString("DataAccessGetRelatedMessagelogListException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get ServiceType Exception..
        /// </summary>
        internal static string DataAccessGetServiceTypeException {
            get {
                return ResourceManager.GetString("DataAccessGetServiceTypeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get ServiceType Exception..
        /// </summary>
        internal static string DataAccessGetServiceTypeException1 {
            get {
                return ResourceManager.GetString("DataAccessGetServiceTypeException1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get ServiceType List Exception..
        /// </summary>
        internal static string DataAccessGetServiceTypeListException {
            get {
                return ResourceManager.GetString("DataAccessGetServiceTypeListException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get ServiceType List Exception..
        /// </summary>
        internal static string DataAccessGetServiceTypeListException1 {
            get {
                return ResourceManager.GetString("DataAccessGetServiceTypeListException1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update BirthdayMessageLog Exception..
        /// </summary>
        internal static string DataAccessUpdateBirthdayMessageLogException {
            get {
                return ResourceManager.GetString("DataAccessUpdateBirthdayMessageLogException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update ContentParameter Exception..
        /// </summary>
        internal static string DataAccessUpdateContentParameterException {
            get {
                return ResourceManager.GetString("DataAccessUpdateContentParameterException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update ContentParameter Exception..
        /// </summary>
        internal static string DataAccessUpdateContentParameterException1 {
            get {
                return ResourceManager.GetString("DataAccessUpdateContentParameterException1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update ContentTemplateAttachement Exception..
        /// </summary>
        internal static string DataAccessUpdateContentTemplateAttachementException {
            get {
                return ResourceManager.GetString("DataAccessUpdateContentTemplateAttachementException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update ContentTemplate Exception..
        /// </summary>
        internal static string DataAccessUpdateContentTemplateException {
            get {
                return ResourceManager.GetString("DataAccessUpdateContentTemplateException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update ContentTemplate Exception..
        /// </summary>
        internal static string DataAccessUpdateContentTemplateException1 {
            get {
                return ResourceManager.GetString("DataAccessUpdateContentTemplateException1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Customer Exception..
        /// </summary>
        internal static string DataAccessUpdateCustomerException {
            get {
                return ResourceManager.GetString("DataAccessUpdateCustomerException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update CustomerType Exception..
        /// </summary>
        internal static string DataAccessUpdateCustomerTypeException {
            get {
                return ResourceManager.GetString("DataAccessUpdateCustomerTypeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update ExtensionMessage Exception..
        /// </summary>
        internal static string DataAccessUpdateExtensionMessageException {
            get {
                return ResourceManager.GetString("DataAccessUpdateExtensionMessageException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update ExtensionMessageLog Exception..
        /// </summary>
        internal static string DataAccessUpdateExtensionMessageLogException {
            get {
                return ResourceManager.GetString("DataAccessUpdateExtensionMessageLogException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update IncomingMessageContent Exception..
        /// </summary>
        internal static string DataAccessUpdateIncomingMessageContentException {
            get {
                return ResourceManager.GetString("DataAccessUpdateIncomingMessageContentException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update IncomingMessageContentSent Exception..
        /// </summary>
        internal static string DataAccessUpdateIncomingMessageContentSentException {
            get {
                return ResourceManager.GetString("DataAccessUpdateIncomingMessageContentSentException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update MessageCommand Exception..
        /// </summary>
        internal static string DataAccessUpdateMessageCommandException {
            get {
                return ResourceManager.GetString("DataAccessUpdateMessageCommandException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update MessageCommand Exception..
        /// </summary>
        internal static string DataAccessUpdateMessageCommandException1 {
            get {
                return ResourceManager.GetString("DataAccessUpdateMessageCommandException1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update MessageContentAttachement Exception..
        /// </summary>
        internal static string DataAccessUpdateMessageContentAttachementException {
            get {
                return ResourceManager.GetString("DataAccessUpdateMessageContentAttachementException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update MessageContent Exception..
        /// </summary>
        internal static string DataAccessUpdateMessageContentException {
            get {
                return ResourceManager.GetString("DataAccessUpdateMessageContentException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update MessageContent Exception..
        /// </summary>
        internal static string DataAccessUpdateMessageContentException1 {
            get {
                return ResourceManager.GetString("DataAccessUpdateMessageContentException1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update MessageContentSentAttachement Exception..
        /// </summary>
        internal static string DataAccessUpdateMessageContentSentAttachementException {
            get {
                return ResourceManager.GetString("DataAccessUpdateMessageContentSentAttachementException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update MessageContentSent Exception..
        /// </summary>
        internal static string DataAccessUpdateMessageContentSentException {
            get {
                return ResourceManager.GetString("DataAccessUpdateMessageContentSentException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update MessageContentSent Exception..
        /// </summary>
        internal static string DataAccessUpdateMessageContentSentException1 {
            get {
                return ResourceManager.GetString("DataAccessUpdateMessageContentSentException1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update RelatedMessagelog Exception..
        /// </summary>
        internal static string DataAccessUpdateRelatedMessagelogException {
            get {
                return ResourceManager.GetString("DataAccessUpdateRelatedMessagelogException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update ServiceType Exception..
        /// </summary>
        internal static string DataAccessUpdateServiceTypeException {
            get {
                return ResourceManager.GetString("DataAccessUpdateServiceTypeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update ServiceType Exception..
        /// </summary>
        internal static string DataAccessUpdateServiceTypeException1 {
            get {
                return ResourceManager.GetString("DataAccessUpdateServiceTypeException1", resourceCulture);
            }
        }
    }
}
